### ISSUE TITLE
Feature: outputs to indicate status:

### ISSUE THREAD

**Issue by kami0011** [bdring/FluidNC#1019]
### Machine Context

I want to get output of status like alarm on output pin. How can I define in YAML file 

### Feature Description

I want to get output of status like alarm on output pin. How can I define in YAML file 

### Other Approaches

I want to get output of status like alarm on output pin. How can I define in YAML file 

### How I Can Help

I want to get output of status like alarm on output pin. How can I define in YAML file

**Comment by MitchBradley** [comment]
FluidNC currently does not support this feature.  You could do it with an external microprocessor connected via a UART channel.  That microprocessor would have to monitor status reports, looking for Alarm state.

**Comment by kami0011** [comment]
Is the any ready made solution from third party

**Comment by MitchBradley** [comment]
There is some discussion in the #displays_pendants channel of the FluidNC Discord server.

**Comment by bdring** [comment]
See this post.

https://discord.com/channels/780079161460916227/1149787482183974965
