### ISSUE TITLE
Feature: can I control multiple cards like mks tinybee from one web ui 

### ISSUE THREAD

**Issue by kami0011** [bdring/FluidNC#1020]
### Machine Context

I want to connect multiple mks tinybee cards from one web ui. Is there any way we can connect all cards in one web user interface. Also can I edit user interface 

### Feature Description

I want to connect multiple mks tinybee cards from one web ui. Is there any way we can connect all cards in one web user interface. Also can I edit user interface 

### Other Approaches

I want to connect multiple mks tinybee cards from one web ui. Is there any way we can connect all cards in one web user interface. Also can I edit user interface 

### How I Can Help

I want to connect multiple mks tinybee cards from one web ui. Is there any way we can connect all cards in one web user interface. Also can I edit user interface

**Comment by MitchBradley** [comment]
WebUI does not support multiple controllers.  To change the UI you would have to modify the javascript and html code at <https://github.com/MitchBradley/ESP3D-WEBUI>
