### ISSUE TITLE
The 3d print file for the module support pieces.

### ISSUE THREAD

**Issue by skiddykiddie** [bdring/FluidNC#1032]
### Machine Context

Just putting together a 6 pack external card and wanted to have the support pieces for the modules. 

### Feature Description

The other files are in the wiki for the 6pack but not the module support pieces.

### Other Approaches

NA

### How I Can Help

Any place to download these parts?

**Comment by bdring** [comment]
https://github.com/bdring/6-Pack_CNC_Controller/tree/main/3D_Files

**Comment by skiddykiddie** [comment]
Awesome!  Thanks for all your great work!
