### ISSUE TITLE
Problem: Discord invitation not working

### ISSUE THREAD

**Issue by cvjensen** [bdring/FluidNC#1038]
### Wiki Search Terms

http://wiki.fluidnc.com/en/support/discord

### Controller Board

6-pack

### Machine Description

not necessary

### Configuration file

```yaml
not necessary
```

### Startup Messages

```text
not necessary
```

### What happened?

Tried to click on the discord invitation link and it says that the link is invalid or expired?

**Comment by bdring** [comment]
I added a fresh invite to the wiki.

http://wiki.fluidnc.com/
