### ISSUE TITLE
Problem: ESP32 5-axis experiment

### ISSUE THREAD

**Issue by yusufferdemm** [bdring/FluidNC#1047]
### Wiki Search Terms

Hello, I wish you a good day,

We designed a board for ESP32 in this way and loaded FluidNC onto the ESP32. I couldn't find a suitable configuration (YAML) file to convert it to 5 axes. I couldn't define A and B axes similar to the 3axis_v4.yaml file in example_configs.

a:
  steps_per_mm: 800
  max_rate_mm_per_min: 2000
  acceleration_mm_per_sec2: 25
  max_travel_mm: 1000
  homing:
    cycle: 1
    mpos_mm: 10
    positive_direction: true
  motor0:
    limit_all_pin: gpio.16:low:pu
    stepstick:
      direction_pin: gpio.33
      step_pin: gpio.27
  motor1:
    null_motor:

When I tried to define them in this way for A and B, the software did not detect the other two axes.

How can I define 5 axes on this board in the configuration file?

Or is there a pre-defined 5-axis configuration file for ESP32?

### Controller Board

ESP32

### Machine Description

CNC Milling Machine

### Configuration file

```yaml
don't have :(
```

### Startup Messages

```text
FluidNC 3.9
```

### User Interface Software

UGS

### What happened?

Somehow, when I define a and b axes in the 3axis_v4 yaml file, a and 5 axes do not appear as defined in UGS.

### Other Information

![24199196-24F3-4D4A-88B0-774C50650408_1_105_c](https://github.com/bdring/FluidNC/assets/66909718/2c7e84fb-e1e0-41d7-926d-ed791979d8da)
![813B956A-2BFC-435B-BBBC-9B108D61B768_1_105_c](https://github.com/bdring/FluidNC/assets/66909718/892a3e0b-20c2-4132-a16d-1caa515335cb)
![727C037E-06E2-4858-B50B-B5BB8E8736E1_1_105_c](https://github.com/bdring/FluidNC/assets/66909718/9a50be30-37fc-4645-94ab-fc208e615ab2)

**Comment by bdring** [comment]
There are some example files here.

https://github.com/bdring/6-Pack_CNC_Controller/tree/main/FluidNC_configs

**Comment by bdring** [comment]
Show your existing config file that works for the 3 axes.
Show the startup messages too.

**Comment by bdring** [comment]
Closing inactive issue
