### ISSUE TITLE
WHILE or GOTO gcodes 

### ISSUE THREAD

**Issue by 42loop** [bdring/FluidNC#1077]
### Machine Context

I have to run a gcode file repeatedly for an artistic installation, but WHILE or GOTO gcode seems to be not implemented

### Feature Description

implement WHILE or/and GOTO

### Other Approaches

I assume i could wire a digital output (like flood/mist) to a digital input, set that on the gcode end and have a macro configured to run at the input change to call the sequence again - not too elegant 

### How I Can Help

i could do some testing

**Comment by MitchBradley** [comment]
We recommend doing this with an auxiliary sender which can be implemented with a very inexpensive microcomputer like an ESP32-S3 or Arduino Nano.  We have a framework for writing code like that in the PendantsForFluidNC repo.
