### ISSUE TITLE
Please add OpenCNC Shield v2 to the list of existing Hardware 

### ISSUE THREAD

**Issue by lenny-nimoy** [bdring/FluidNC#1109]
### Machine Context

Hi !  My name is Holger, I am from Germany. Thank's a very lot for porting grbl to esp32 -> FluidNC and this way enableing the DIY community to build professional but affordable CNC machines.

I am currently building the second machine using FluidNC and Controller Hardware developed and distributed by Timo Altholtmann. He has a very flexible and modular setup wich does not only support use of FluidNC. I think it's worth to mention in the list of exsisting Hardware. In my opinion Timo's products are of good quality and are quite thought through while still affordable.
Here a link to the shop : https://shop.altholtmann.com/Steuerung/OPEN-CNC-Shield-2/
Here his his github with his projects licensed  CC-BY-SA-NC 4.0   :   https://github.com/timo1235/cnc-werkstatt

### Feature Description

All said above ...

### Other Approaches

All said above ...

### How I Can Help

All said above ...

**Comment by bdring** [comment]
Some of the link I followed are 404. You are free to edit the wiki yourself. 

http://wiki.fluidnc.com/en/wiki_contributions
