### ISSUE TITLE
Could not download the release asset TypeError: Failed to fetch

### ISSUE THREAD

**Issue by zhuyuwu110** [bdring/FluidNC#1136]
### Wiki Search Terms

-------

### Controller Board

6-pack

### Machine Description

----------

### Configuration file

```yaml
---------
```

### Startup Messages

```text
---------
```

### What happened?

Could not download the release asset TypeError: Failed to fetch
![屏幕截图 2024-02-18 170236](https://github.com/bdring/FluidNC/assets/158246784/a8320f2e-0b11-4b34-8ae4-cfef38118e32)

**Comment by breiler** [comment]
I just tried it, it worked fine for me.

Can you right click somewhere on the page and select "Inspect". Then click on the network tab and console and try again. Then take a screenshot if it fails. It should look something like this:

![image](https://github.com/bdring/FluidNC/assets/8962024/46fe827f-1fac-4edc-bd26-8f5278492099)

**Comment by zhuyuwu110** [comment]
![屏幕截图 2024-02-18 174435](https://github.com/bdring/FluidNC/assets/158246784/88774af0-f14a-4559-9cda-1e15e586c5e8)
![屏幕截图 2024-02-18 174619](https://github.com/bdring/FluidNC/assets/158246784/7d06feeb-6124-4b46-aaba-7d445d39da46)

**Comment by breiler** [comment]
You closed the issue, does this mean that you managed to resolve it?

I am interested in the full URL here, can you right click and choose copy link?
![image](https://github.com/bdring/FluidNC/assets/8962024/97c926ae-e7c9-4171-b41b-526cdd9c5e90)
