### ISSUE TITLE
Problem: Cannot configure an ssid which contains an exclamation mark

### ISSUE THREAD

**Issue by crasu** [bdring/FluidNC#1157]
### Wiki Search Terms

Exclamation mark 
$! 
! 

### Controller Board

6-pack

### Machine Description

MPCNC

### Configuration file

```yaml
Not uploaded yet to the controller
```

### Startup Messages

```text
[MSG:INFO: Connecting....]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connecting....]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
```

### User Interface Software

Serial

### What happened?

When entering the ssid the serial connection dies and the terminal stops responding.

**Comment by MitchBradley** [comment]
The answer is in the Frequently Asked Questions page in the wiki

**Comment by crasu** [comment]
Thank you in case someone new ends up here as well. ! enables feedhold. You need to escape with %21.

http://wiki.fluidnc.com/en/support/faq#special-character-issue
