### ISSUE TITLE
Problem: v3.7.15  WiFi    failed:406 wrong data

### ISSUE THREAD

**Issue by zhuyuwu110** [bdring/FluidNC#1168]
### Wiki Search Terms

-

### Controller Board

6-pack

### Machine Description

-

### Input Circuits

```yaml
-
```

### Configuration file

```yaml
-
```

### Startup Messages

```text
-
```

### User Interface Software

-

### What happened?

v3.7.15  WiFi    failed:406 wrong data

![b1905454055280b7bbb11c7c8d6c8af](https://github.com/bdring/FluidNC/assets/158246784/fb03b00f-0038-4176-a8fc-e16cd5e7b4b0)

### GCode File

-

### Other Information

-

**Comment by bdring** [comment]
I will look into into that. You can also use the command prompt in FluidTerm or the WebUI with the $STA/SSID= command.

http://wiki.fluidnc.com/en/features/commands_and_settings#stassid

**Comment by Insonic** [comment]
This also happens on the MKS TinyBee.

For the reproduction you need to do a fresh install 
1) erase all data
2) update to Version 3.7.15 or 3.7.16
3) try to list all available WLAN´s

What happens: Instead of showing a list with all available WLANs it shows "Failed: 406 Wrong data"

I have several available WLAN´s from different AccessPoints (Zyxel, Ubiquiti, AVM Fritzbox)

**Comment by MitchBradley** [comment]
One bit of missing information is where the webui image came from.

**Comment by Insonic** [comment]
ahh sorry - it was all installed with the web installer.
In fact it was an update with the "erase all" option to get a clean start with the new version.

**Comment by daxliniere** [comment]
I am having this issue as well. My controller works fine as as AP, but **$Wifi/ListAPS** is only getting signal: 58 from where the controller is located. (Wifi points are Unifi enterprise, so should be great.)

**Comment by MitchBradley** [comment]
> I am having this issue as well. My controller works fine as as AP, but can't connect to my wifi and **$Wifi/ListAPS** is getting signal=85 from where the controller is located. (Wifi points are Unifi enterprise, so should be great.)
> 
> I don't have an SD card installed... related??

Did you get the 406 error like the issue says?  Your description mentions different symptoms.

**Comment by daxliniere** [comment]
Yes error 406. (I found this post while looking for solutions)
