### ISSUE TITLE
Problem: How to install FluidNC the esp32-s2 or esp32-c3. 

### ISSUE THREAD

**Issue by MiguelASTavares** [bdring/FluidNC#1213]
### Wiki Search Terms

esp32-s2 esp32-c3 build releases 

### Controller Board

n

### Machine Description

n

### Input Circuits

```yaml
n
```

### Configuration file

```yaml
n
```

### Startup Messages

```text
n
```

### What happened?

I have tried to install the image on both the ESP32-S2 and the ESP32-C3. Both failed. The ESP32-S2 fails because the secure boot is detected. When I try to force the installation using the esptool, I get an error saying that the image is not for the ESP32-S2 chip. When I try to install on the ESP32-C3, the installation file works, but afterward, it gives an error in the command-line tool. After encountering these two errors, I turn to the build-release.py file and switch the MCU to ESP32-C3. However, I receive the following error:

```
image esp32c3-noradio-firmware
Missing image esp32-4m-partitions
```

Is there anything that I'm missing? Are there a set of binaries for any of these ESP32 boards? I saw in other issues that you support the ESP32-S2, but I can't seem to find the appropriate files, and when compiling the PlatformIO project, it fails.

**Comment by MitchBradley** [comment]
S2 and C3 will not work because they do not have enough hardware resources to run FluidNC well.  S3 works but the developers do not support it.
