### ISSUE TITLE
Feature: Trinamic position control via SPI

### ISSUE THREAD

**Issue by imechura** [bdring/FluidNC#1217]
### Machine Context

I would like to build a machine using trinamic 035 drivers in a trinamic 301 motion controller which does not accept step/dir command instead it needs SPI messages sent to control the motor position/movement.

### Feature Description

It would support controlling motors beyond setting register values via SPI as is described in this manual https://www.analog.com/media/en/technical-documentation/user-guides/TMCM-035_manual.pdf

### Other Approaches

Currently only using drivers that support step/dir signals for motion control

### How I Can Help

I can provide hardware to development team. I can test the software. I can write user documentation and wiki content

**Comment by bdring** [comment]
That device appears to support step dir. SPI for us is not possible.
