### ISSUE TITLE
Wifi porblem

### ISSUE THREAD

**Issue by abd97khateeb** [bdring/FluidNC#1220]
### Wiki Search Terms

I ran install-wifi but could not find the wifi network. What should I do in this case, does it have anything to do with config file?

### Controller Board

4 axis

### Machine Description

.

### Input Circuits

```yaml
.
```

### Configuration file

```yaml
.
```

### Startup Messages

```text
I ran install-wifi but could not find the wifi network. What should I do in this case, does it have anything to do with config file?
```

### What happened?

.

### GCode File

.

### Other Information

.

**Comment by MitchBradley** [comment]
The config file does not affect wifi accessibility.  See http://wiki.fluidnc.com/en/features/wifi_bt for wifi setup hints.
