### ISSUE TITLE
I flashed 3.2.4 after "working" 3.1.6 and stepper doesn't move.

### ISSUE THREAD

**Issue by antoan-boss** [bdring/FluidNC#126]
What version of the firmware are you using?
3.2.4

Is the problem repeatable?
Yes

Under what conditions does the bug occur?
I just tried to install 3.2.4 and it does not work for me :/ If I install 3.1.6 back it works(stepper moves). I have only one stepper connected on x axis for testing.
I changed config to new style from example "6_pack_external_huanyang.yaml". Renamed to config.yaml. I just use RMT engine.
Does anyone knows where could be a problem? Does something changed that could cause this?

Configs below:
[configs.zip](https://github.com/bdring/FluidNC/files/7558356/configs.zip)

**Comment by bdring** [comment]
The configs say 6 pack. What hardware are you actually using?

**Comment by bdring** [comment]
Please show the boot messages.

https://github.com/bdring/FluidNC/wiki/Requesting-Help

**Comment by antoan-boss** [comment]
I checked it. Error parsing config. Missing new line at the end of config... Who does not love yaml? Thanks for help :)
