### ISSUE TITLE
Problem: yaml file. 

### ISSUE THREAD

**Issue by Hooks321** [bdring/FluidNC#1272]
### Wiki Search Terms

Only new here.

### Controller Board

6-pack ESP-WROOM-32

### Machine Description

Gantry Laser setup.

### Configuration file

```yaml
Wont past
```

### Startup Messages

```text
Cannot open configuration file:<your_filename>
```

### User Interface Software

Fluidterm

### What happened?

Every time I upload the config yaml file it said the configuration is invalid.??? any help would be great thanks.

### GCode File

?

### Other Information

?

**Comment by breiler** [comment]
Can you show the output from the command `$SS`

**Comment by Hooks321** [comment]
Hope this helps.

**Comment by breiler** [comment]
Did you try to attach something? That doesn't work when using email - you need to go to the issue to do that: https://github.com/bdring/FluidNC/issues/1272

**Comment by Hooks321** [comment]
Did that come through?

**Comment by Hooks321** [comment]
![20240726_211518](https://github.com/user-attachments/assets/d88b7dfd-01a8-4e5f-b56e-484a774977a9)
Sorry for the delay.

**Comment by breiler** [comment]
The `<your_filename>` is probably the default setting, select your config file with:
`$Config/Filename=Laser Home XYZ (1).yaml`

Or you could use the https://installer.fluidnc.com/ go to the "File browser" and click the "Select Config" button:

![image](https://github.com/user-attachments/assets/34a2279f-5fd8-45ee-bd9b-935916b600c1)

**Comment by Hooks321** [comment]
Still trying.

**Comment by Hooks321** [comment]
OK, selected active config. what do I do next.

**Comment by breiler** [comment]
Restart the controller and check the boot messages.

If you are doing this from the https://installer.fluidnc.com/ just go to the "Terminal" page and hit "Restart"

**Comment by Hooks321** [comment]
Hi, looks like its loaded OK now. Thanks for all your help so far, much appreciated. Is there a way for this card to be seen in Lightburn software now.?

**Comment by MitchBradley** [comment]
Did you search for "lightburn" in the fluidnc wiki?

**Comment by Hooks321** [comment]
Yes, I found it. Thankyou.
