### ISSUE TITLE
Feature: 4-axis control on webui

### ISSUE THREAD

**Issue by AKCAKAJl** [bdring/FluidNC#1306]
### Machine Context

I'm building a machine with 4-axis asynchronous, I wrote a config file. It works great. Left side is X and Y axes, right side is A and Z axes

### Feature Description

Operating with 4-axis machine in FluidNC webui

### Other Approaches

I tried to operate axes with console commands, but its not too easy. Tried to use another program GrblFoamController, it works, but I'd like to use FluidNC

### How I Can Help

At FliudNC we have a joystick to control XYZ axes, how can I add 1 more axe? Sorry for my English )))

**Comment by bdring** [comment]
You can change the Z axis to A, B or C.

http://wiki.fluidnc.com/en/features/webui#controls-panel
