### ISSUE TITLE
Problem: How to restart wifi after settings

### ISSUE THREAD

**Issue by zengfanfan** [bdring/FluidNC#1353]
### Wiki Search Terms

restart radio

### What happened?

1. I setup ap ssid: `$AP/SSID=ESP32.XYZ`
2. restart wifi: `$Radio/State=on`
It says: error:3 
[MSG:ERR: Invalid $ statement]

Is this command removed? How can I restart wifi ?

### Other Information

It works on v3.7.17, fail on v3.8.3

**Comment by MitchBradley** [comment]
Just reset the firmware with $bye

**Comment by zengfanfan** [comment]
Is it the only way? what if i dont want to reset it?

**Comment by MitchBradley** [comment]
It is the only way.
