### ISSUE TITLE
Feature: Setting step_per_mm paramater for each Y motor individually.

### ISSUE THREAD

**Issue by Simon5162** [bdring/FluidNC#1357]
### Machine Context

Hi everyone,

I have two Y motors on my CNC machine, each driving its own belt. I'm trying to set the steps_per_mm parameter for each Y motor individually. At the moment, I can change the step_per_mm parameter, but it applies to the entire axis rather than to each motor separately. Is there a way to modify the config.yaml file to achieve this?

Thank you in advance for your help!

### Feature Description

Setting steps_per_mm paramater for each Y motor individually.

### Other Approaches

Can't solve this problem in other ways currently.

### How I Can Help

Changing config.yaml file to get one steps_per_mm param for each motors on each axis.

**Comment by bdring** [comment]
Internal to FluidNC, axes track and calculate everything in steps. It would not be possible to have 2 different values of steps for an axis without a massive overhaul. It is just not worth the effort and risk the stability of the regular code.

Please describe the problem you are having with your machine in greater detail

**Comment by MitchBradley** [comment]
It would probably be possible to write a custom Kinematics module that ganged two motors with different steps_per_mm onto one axis.

**Comment by summerfind** [comment]
Hi,
My calibration not working, the machine's real movement doesn't change whatever the steps_per_mm set.
how to fix?

**Comment by MitchBradley** [comment]
Please do not hijack existing issues.  Open a new one with your information.  Especially do not use a feature request issue for a problem report.

**Comment by Simon5162** [comment]
Hello, I would like to clarify the issue. I wish to adjust the steps_per_mm parameter for each of the two motors on the Y-axis independently of each other for the following reasons:

Due to the use of two motors coupled with two belts to drive the Y-axis, the steps_per_mm parameter is entirely dependent on the belt tension. The tighter a belt is, the smaller the steps_per_mm value! I have written a G-code routine to calibrate the steps_per_mm parameter by measuring the actual distance traveled by the CNC on the Y-axis and comparing this value with the theoretical distance that should have been traveled given the steps_per_mm. My routine works very well, but I am forced to measure the distance as close as possible to one of the motors and adjust the belt tension of the other motor to correct any discrepancy.

This adjustment is inconvenient, and it would be much more interesting to be able to adjust this discrepancy by changing the steps_per_mm value for the second motor independently of the first. Without this, I end up with two different tension levels on the two belts, which is not very comfortable.

I think this would be a very interesting feature for the firmware as it would allow precise calibration of an axis driven by two motor/belt systems!

**Comment by MitchBradley** [comment]
It could be done by writing a custom kinematics system that gangs the motors at a higher level than the existing mechanism which gangs them below the step-computation layer.  That said, I am not volunteering to do the coding and support for such a feature.
