### ISSUE TITLE
Feature: Add big three tech Rodent to hardware list

### ISSUE THREAD

**Issue by selektha1** [bdring/FluidNC#1386]
### Machine Context

add BTT Rodent to the fetured hardware list
https://biqu.equipment/collections/control-board/products/bigtreetech-rodent

### Feature Description

Its missing from the hardware page but are one of the bigger comercial projects using fluidnc to my knowledge and as example ratrig is using it for there upcoming cnc mill

### Other Approaches

.

### How I Can Help

Possible documentation for the hardware once I receive it.

**Comment by bdring** [comment]
anyone can add and edit the wiki.

http://wiki.fluidnc.com/en/wiki_contributions
