### ISSUE TITLE
Feature: Dimmer support for AC motors

### ISSUE THREAD

**Issue by VeryFastSnail** [bdring/FluidNC#1416]
### Machine Context

Machine is upgraded chineese CNC machine with MKS DLC32 v2.1 controller

### Feature Description

I'm experimenting on with AC motors, MAKITA clones for example 10k-30k variant. PWM speed control can only be done with additional micro controller that reads in the PWM of spindle (5v TTL) and converts it to dimmers pwm.

Bigger dimmers that support bigger power routers needs zero cross pin for the library. https://github.com/RobotDynOfficial/RBDDimmer

It would be great to have feature where pwm and zero cross would work in conjunction to control the speed. 

### Other Approaches

There are all in one modules that has micro already included, but those are expensive and low power. And why should there be two micros in one machine doing the same job. 

### How I Can Help

I can provide some code and what I found out experimenting on my own machine. Glad to do some coding myself if needed. MY machine is working , but I hate this workaround since it's reading in PWM and that's susceptible for noise.

**Comment by MitchBradley** [comment]
> And why should there be two micros in one machine doing the same job.

Because the FluidNC code is already bloated with features that only a small number of people use.  The developers are overwhelmed with support requests from people who rarely donate to help up defray our costs.  Developing code for and supporting hardware that we do not have is especially difficult.  Delegating code for rarely-used hardware to an external MCU makes it clear that it is Somebody Else's Problem.

**Comment by bdring** [comment]
Try this.

https://cnc4pc.com/c47-a-c-speed-controller-relay-board.html?srsltid=AfmBOopa8IycqV3-UcJEXftEA_0w50a-QCj4_7uwlDS5XMO3AZf00fIJ

Or this.

https://vhipe.com/

Dimmers chop the power, so they get very weak at slower speeds. The Superpid is closed loop, so it maintains power at slower speeds.

Both have dangerous exposed voltages.

**Comment by VeryFastSnail** [comment]
> > And why should there be two micros in one machine doing the same job.
> 
> Because the FluidNC code is already bloated with features that only a small number of people use. The developers are overwhelmed with support requests from people who rarely donate to help up defray our costs. Developing code for and supporting hardware that we do not have is especially difficult. Delegating code for rarely-used hardware to an external MCU makes it clear that it is Somebody Else's Problem.

Sounds right, in this case I will make all code available with tutorial how to have it setup in fluidnc so others can recreate. Even if there are only few people who will use it.

**Comment by VeryFastSnail** [comment]
> Try this.
> 
> https://cnc4pc.com/c47-a-c-speed-controller-relay-board.html?srsltid=AfmBOopa8IycqV3-UcJEXftEA_0w50a-QCj4_7uwlDS5XMO3AZf00fIJ
> 
> Or this.
> 
> https://vhipe.com/
> 
> Dimmers chop the power, so they get very weak at slower speeds. The Superpid is closed loop, so it maintains power at slower speeds.
> 
> Both have dangerous exposed voltages.

I already have this solved with external micro, the only thing I want now is to have really stable PWM control in noisy environment, since brushed motors create EM radiation.  

Thanks for the information. Will take a look
