### ISSUE TITLE
Newbie's Guide to macOS Installation

### ISSUE THREAD

**Issue by Longus** [bdring/FluidNC#151]
**Please describe the feature you would like implemented**
A step by step guide to the installation process on Mac OS.

**Why do you think this would improve FluidNC?**
There's a lot to learn for a newbie.

**What do you need the feature for?**
I don't need it, I already invested the time to figure it out. I **would** have loved to have had it.

My markdown version is here:
https://github.com/Longus/FluidNC/wiki/Set-Up-FluidNC-Using-macOS

**Comment by MitchBradley** [comment]
Is the index.html.gz step necessary?  The current version of the install script automatically installs the version of index.html.gz that we are keeping up-to-date with FluidNC.

**Comment by Longus** [comment]
It was when I wrote this, dunno about now...

**Comment by bdring** [comment]
We have some changes coming to the install process. We should wait until those are tested and then update this. 

References to specific versions should be removed as it can change several times per month.
