### ISSUE TITLE
Debounce Setting for Hard Limits

### ISSUE THREAD

**Issue by Northernboy** [bdring/FluidNC#158]
Is there a way to set the debounce on each of the limit switches used for hard limits?

Thx
NB

**Comment by bdring** [comment]
Currently we do not have software debouncing on limit switches. 

What hardware are you using? I use hardware solutions on all my controllers. (low pass filters, Schmitt triggers, and/or opto isolation). It seems to work fine.

**Comment by Northernboy** [comment]
Thank you for the response. I am presently using my own temporary test setup using opto isolators only. But working on my permanent circuit and will adding filters & triggers as well. My first test using FluidNC was using ESP32-GRBL and only had to increase the debounce a bit. All good enjoying the new system and working on my setup to make it better.

Cheers
NB
