### ISSUE TITLE
Ganged axis with 2 limit switches on one input

### ISSUE THREAD

**Issue by PhilClayzen** [bdring/FluidNC#170]
**Please describe the feature you would like implemented**
I designed my one controller for Esp32 Grbl and there it was possible to attach both limit switches of a ganged axis to the same input. So my hardware has 3 inputs for XYZ with two motors on the y axis in mind. If I understand the new FluidNC documentation, this is not possible anymore in order to get a "stress free" homing. Which I can understand, but I think it would be good to allow that so that the user can choose if he wants to use the older procedure or the newer. Is that possible?

**Why do you think this would improve FluidNC?**
Because it makes it more flexible (and I can use my hardware like planned and don't need to use a "User Button" which i planned for Macros :P

Greets from Germany
Philipp

**Comment by bdring** [comment]
You can already do 2 motors / 1 switch. It will not auto square though.

Right now the logic is simple, so the machine can infer the homing type from the config

1 motor / 1 switch = standard homing
2 motors / 1 side has a switch = standard homing
2 motors / both sides have switches = auto squaring.

We would need to add additional items to the config file to cover a new type option. It creates a situation where a key like **auto_square: true** could be set on a single motor axis. It potentially breaks some existing configs.

It is likely to make the code a lot more complicated too.
