### ISSUE TITLE
can't set SSID with special character

### ISSUE THREAD

**Issue by branko623** [bdring/FluidNC#172]
Couldn't set SSID with a ?, or some other special characters. No way to pass a quoted ssid? 

$STA/SSID=NANI?
$STA/SSID=NANI
<Idle|MPos:0.000,0.000,0.000|FS:0,0>
$STA/SSID=NANI
ok

**Comment by bdring** [comment]
The Grbl protocol requires special handling of the '?' character. See this FAQ entry.

https://github.com/bdring/FluidNC/wiki/FluidNC-FAQ#special-character-issue
