### ISSUE TITLE
WIFI password with '!' at the end does not work

### ISSUE THREAD

**Issue by librarymark** [bdring/FluidNC#179]
What version of the firmware are you using?
v3.2.7
Is the problem repeatable?
Yes
Under what conditions does the bug occur?

Trying to enter wifi password, mine ends with a '!'. When I try $Sta/Password=(password)! it comes back with [feedhold] and hangs 

```C++
  #define EASIER_TO_READ true
```

**Comment by bdring** [comment]
For compatibility with Grbl senders certain characters have issues. see the faq item.

https://github.com/bdring/FluidNC/wiki/FluidNC-FAQ#special-character-issue

**Comment by librarymark** [comment]
So in other words, I need to change my wifi password?

**Comment by librarymark** [comment]
Is there a way to preset it in code somewhere?

**Comment by bdring** [comment]
As the wiki says, you can do it via the WebUI in AP mode.

It takes less than a minute.

**Comment by MitchBradley** [comment]
See PR #181
