### ISSUE TITLE
Ability to enter WIFI credentials at install

### ISSUE THREAD

**Issue by librarymark** [bdring/FluidNC#180]
**Please describe the feature you would like implemented**
Ability to enter WIFI credentials at install to accommodate passwords with special characters

**Why do you think this would improve FluidNC?**
Make it easier to connect. 

**What do you need the feature for?**
My wifi password ends with a '!'. This does not work currently. 

**Do you know of other users who need this feature?**
Anyone who uses special characters in their wifi password.

**Comment by bdring** [comment]
Special characters are now supported.
