### ISSUE TITLE
0.96 OLED I2C display error, how to do?

### ISSUE THREAD

**Issue by vvvyky** [bdring/FluidNC#182]
0.96 OLED I2C display error, how to do?

![微信图片_20211217233111](https://user-images.githubusercontent.com/38814385/146568668-ced45d9c-066f-4060-99d9-630e68b618bf.jpg)
![微信图片_20211217233104](https://user-images.githubusercontent.com/38814385/146568715-b04ade38-e450-4b34-a65e-e4be277443bd.jpg)

**Comment by MitchBradley** [comment]
It works fine for me

![IMG_5179](https://user-images.githubusercontent.com/4861133/147144856-7b592b20-6ce4-4cb3-a110-55b267b18313.jpg)

There might be something wrong with your I2C bus hardware connection.

**Comment by MitchBradley** [comment]
I made some improvements to the OLED code.  I do not know if they will help your problem.

**Comment by MitchBradley** [comment]
Another possible problem - make sure that the pins that are used for the OLED I2C bus are not assigned to any other FluidNC functions in the config.yaml file.

**Comment by vvvyky** [comment]
> Another possible problem - make sure that the pins that are used for the OLED I2C bus are not assigned to any other FluidNC functions in the config.yaml file.

The test is done. We solved the problem perfectly![IMG_20211223_194921.jpg](https://user-images.githubusercontent.com/38814385/147236741-28bac89e-7e96-43c3-938a-be3a04545074.jpg)
