### ISSUE TITLE
Telnet client

### ISSUE THREAD

**Issue by JensInternal** [bdring/FluidNC#189]
My new project is to connect another ESP32 with FluidNC via telnet and transfer joystick movement to jogging commands.
It basically works, but there is an issue I couldn`t understand so far and kindly ask for some help.

- VSC is used for programming the Telnet client (Arduino framework)
- it´s connected to my Windows PC and the program is uploaded
- I switch to serial terminal, client is booting
- Client gets a WiFi connect, telnet client connect

Initial lines look like this at the moment

```
WiFi.mode(WIFI_STA);
WiFi.begin(WLAN_SSID, WLAN_PASSWORD);
serial_printf(Serial, "[Status] Connet with WIFI %s ", WLAN_SSID);
  
while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(1000);
  }

if (WiFi.isConnected())
  {
    Serial.print(" connected. Local IP=");
    Serial.println(WiFi.localIP());
    serial_printf(Serial, "[Status] Connect with Telnet IP=%s, Port=%d ... ", WLAN_HOST, WLAN_TELNETPORT);

    if (!client.connect(WLAN_HOST, WLAN_TELNETPORT))
      Serial.print("not ");

      Serial.println("connected");
  }
```
And then: Grbl responds or it doesn't with the typical welcome message
`Grbl 3.2 [FluidNC v3.2.7 (wifi) '$' for help]`

Currently, I need to reset FluidNC via web interface everytime and sometimes several times. Odd to me.
Interesting to me that a FluidNC reset, while still the other ESP32 is running, still keeps the telnet session up. But no welcome message.

Tested it with Putty for the non responding situation. Telnet session windows pops up and disappears shortly after.

In both situations [ESP130] is reported to be ON.

Is the single telnet server session maybe "occupied" by the last upload?
What is the better way to achieve a stable and replying telnet server, I guess my programming needs improvement.

To be more specific: except a hard reset, how can I reliable have a free telnet session to FluidNC or even test it?

**Comment by JensInternal** [comment]
CTRL-X or pressing the WebUI reset button give no reliable result --> reset of the telnet session.
Is there another way, except a hard reset?

**Comment by MitchBradley** [comment]
You can try sending $bye

Please try to ask your questions more clearly.  The last one was confusing.

**Comment by MitchBradley** [comment]
I have been testing Telnet with the Microsoft Windows telnet client and it seems to be working well.  I will test with PuTTY.

**Comment by MitchBradley** [comment]
PuTTY works too.  You have to use Raw instead of Telnet because the FluidNC "telnet" does not perform Telnet options negotiation; it is really just a raw TCP socket.

![image](https://user-images.githubusercontent.com/4861133/147162370-c4ae2452-f68d-48de-9124-e6b36db04e5a.png)

**Comment by MitchBradley** [comment]
If another telnet client is already connected, you cannot connect another.  You must first close the previous one.

**Comment by JensInternal** [comment]
Thank you, Mitch.
Could that be an indicator that client.connected()==true goes out from an existing telnet session, although a derivation of telnet is in use?

A hard reset of my other ESP32 doesn't close the connection on FluidNC

**Comment by MitchBradley** [comment]
You probably need to study how TCP/IP works.  It is designed to survive temporary delays in packet transmission across the Internet, possibly involving many seconds or minutes of outage.  A connection is only closed reliably when the client issues the appropriate shutdown sequence.  A hard reset of the ESP32 client doesn't send a connection shutdown, it just stops talking.

This is a tricky problem.  You might be better off connecting via a websocket.  Websockets have periodic keepalive messages that can be used to detect nonresponsive connections.

**Comment by JensInternal** [comment]
Good point.
I was just looking for a test setup and though that clicking the reset button on the one side and on the other side resetting my pendant would do it.
I´ll try websockets instead :-)

**Comment by JensInternal** [comment]
Sending "$bye" seems to close the connection from server side.
So now there is a reliable test environment - sending "$bye", uploading new code to the other ESP32 and FluidNC accepts the telnet connection.

**Comment by JensInternal** [comment]
After some time of testing I can say that $X/$bye didn't solve my issue.
In the Telnet source code I saw that Luc is mentioned as author, so I addressed it to the WebUI [project](https://github.com/luc-github/ESP3D-WEBUI/issues/217), including some source code which could probably help to identify my issue.

**Comment by JensInternal** [comment]
Issue probably found.

Adding a client.stop() after doing Grbl processing and before the while loop looks good. The while loop is left suddenly and the ESP32 is blinking. The argument with VSC/serial monitoring was not the right way, although it looked like this at first.

Learning:
* only telnet [server](https://forum.arduino.cc/t/what-does-client-stop-do-and-how-does-if-client-work-from-the-server-side/239211) can disconnect the session (in full featured servers something like the command 'close' to close the session)
* FluidNC has a small brother of Telnet with Grbl focused commands and doesn't seem to have a one for closing a session
* Adding a client.stop() to the source code is mandatory to let server know, it can close the session
* Luc pointed out that client.stop() also takes time, although the programm goes on. So I added a delay of 5 seconds

```
<reading and writing to Grbl>

client.stop();
delay(5000);

Log.verbose("Before while loop");
while (client.connected()) {
   while (client.available()) {
      Serial.write(client.read());
   }
}

<blinkSeveralTimes>
```

The last code line can be reached only by a preliminary client.stop();

Current test loop (opening, sending, receiving, closing, ESP.restart) runs for couple of minutes, so this looks promising.

**Comment by MitchBradley** [comment]
I think it is unlikely that you will ever get to a robust solution with the raw TCP socket (misnamed as telnet).  Websockets are the way to go.  If there are problems with websockets, we will fix them, whereas we are disinclined to waste time on the ersatz telnet.
