### ISSUE TITLE
Discord Link: Invalid Invite

### ISSUE THREAD

**Issue by microfoundry** [bdring/FluidNC#211]
Greetings - I wanted to join the Discord group but when I click the link from github I receive this message "Invalid Invite - The invite may be expired, or you might not have permissions to join."

TIA,

-Terry

**Comment by bdring** [comment]
I made a new "never expire" link. Try again and let me know.

**Comment by microfoundry** [comment]
Worked prefect - Thanks for the snappy resolve!
