### ISSUE TITLE
Is there a board configuration for MKS DLC32 V2.1

### ISSUE THREAD

**Issue by Cncninja** [bdring/FluidNC#215]
**First:** Pleas consider discussing this on [Discord](https://discord.gg/MDsRDeNsTE) as a new thread on the fluidnc_help channel rather than posting as a Github issue

I found and bought this ESP32 based grbl board do you think FluidNC will support it? 

![IMG_4686](https://user-images.githubusercontent.com/75448047/147608910-7aa96854-44f4-46cc-9020-ca564507681a.jpg)

**Comment by MitchBradley** [comment]
https://github.com/bdring/FluidNC/blob/main/example_configs/MKS_DLC32_2_ABC.yaml

**Comment by Cncninja** [comment]
Wow thank you
