### ISSUE TITLE
Gcode file generates ERR:1, but the file seems OK

### ISSUE THREAD

**Issue by Leemonoid** [bdring/FluidNC#217]
What version of the firmware are you using?
3.2.8

Issue:
Running the attached gcode generates an error 1:

```
$SD/Run=/signature.ngc
<Idle|MPos:13.000,137.000,0.000|FS:0,0|SD:0.00,/sd/signature.ngc>
[MSG: ERR:1 (Expected GCodecommand letter) in /sd/signature.ngc at line 1]
<Idle|MPos:13.000,137.000,0.000|FS:0,0>
```
(File renamed so it could be uploaded here)
[signature.txt](https://github.com/bdring/FluidNC/files/7786899/signature.txt)

Line 1 of the file is a G21 command, the same as many other files I've generated that work properly.  The gcode was generated with gcodetools in Inkscape. Any idea why it's failing?  Thanks

**Comment by Leemonoid** [comment]
The same error is being reported by 3.2.9.  I don't see anything wrong with the gcode file.  It loads fine into an online gcode file checker.  Please take a look if/when you have time.

**Comment by MitchBradley** [comment]
The most likely cause is that the file somehow got corrupted when it was uploaded to the SD card.  You could also try removing the comment on the first line.  I don't really think that will help, but when things are not working and there is no obvious cause, you just have to start trying things.

**Comment by Leemonoid** [comment]
I removed all contents from the file, except for the single line "G21", with no comment, and the file still generates an error in FluidNC:

`[MSG: ERR:1 (Expected GCodecommand letter) in /sd/signature.ngc at line 1]`

[signature.txt](https://github.com/bdring/FluidNC/files/7797278/signature.txt)
.

**Comment by MitchBradley** [comment]
Try adding a newline at the end of that first line.  The file that you posted does not have one.

**Comment by Leemonoid** [comment]
Added a newline, and the file still generates an ERR:1

**Comment by MitchBradley** [comment]
I don't know what to tell you.  It works for me.
```
ok
g20
ok
$g
[GC:G0 G54 G17 G20 G90 G94 M5 M9 T0 F0 S0]
ok
$sd/run=/signature.ngc
<Idle|MPos:0.000,0.000,0.000|FS:0,0|Pn:XY|SD:0.00,/sd/signature.ngc>
[MSG:/sd/signature.ngc file job succeeded]
ok
$g
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
ok
$sd/show=/signature.ngc
G21
ok
```

I guess you could try $sd/show=signature.ngc to see if the file can be read correctly.

**Comment by Leemonoid** [comment]
OK, thanks.  Yes it's very strange.  I'll try to reload everything from scratch tomorrow.  Happy New Year...

**Comment by Leemonoid** [comment]
OK, I found the error. My text editor was somehow in UTF-8-BOM mode, which inserted invisible characters in front of the first line of my gcode file.  When I ran:
`$sd/show=/signature.ngc`
the result showed the invisible characters:
`ï»¿G21`

Thank you for your time, Mitch.
