### ISSUE TITLE
FluidNC v3.2.9 WebUI won't start

### ISSUE THREAD

**Issue by epineh** [bdring/FluidNC#226]
As title suggests, I did a new install onto the esp32, logged onto the esp32 AP no probs but the web UI isn't starting, there is a message saying:
File index.html.gz is missing, please upload it
Cheers.

**Comment by marsjo** [comment]
On first install you need to use `install-fs`. This will also create the file-system and also add the 'index.html.gz'. You can also download the `index.html.gz` and upload the file to the esp32 via webinterface or fluidterm.

You can find this and further information in the HOWTO-INSTALL file from the release package.

**Comment by epineh** [comment]
Ok thanks, got it working.
