### ISSUE TITLE
Heightmap for PCB milling over wifi

### ISSUE THREAD

**Issue by krishchan007** [bdring/FluidNC#227]
Is there any way to use a gcode sender such as candle in order to heightmap PCBs over WIFI (without using a wired serial connection)

**Comment by bdring** [comment]
You can setup a virtual serial connection over Bluetooth or Wifi.

The bluetooth automatically sets up a serial port
You can use something like the free Netburner virtual serial port on Wifi

Both will have a more latency than a wired serial; port, but probably fine for this application

**Comment by krishchan007** [comment]
Latency in the order of ????  ns, us, ms ?????

**Comment by MitchBradley** [comment]
It depends on your network.  Measure it.

**Comment by MitchBradley** [comment]
That said, nothing having to do with either serial or network will have latency in either the ns or us range.

**Comment by krishchan007** [comment]
Thanks for the reply. How can i measure it reliably, any suggestions?

**Comment by krishchan007** [comment]
> That said, nothing having to do with either serial or network will have latency in either the ns or us range.

For the application mentioned, i assume this will be more than enough, if feed rates are much smaller (like 10 mm per min).

**Comment by MitchBradley** [comment]
One easy way is to try it with different connection types.  It will probably be dominated by the motion and probing in any case.
