### ISSUE TITLE
Board Makerbase MKS TinyBee

### ISSUE THREAD

**Issue by michaelnu** [bdring/FluidNC#260]
Hello,
does FluidNC work with the board Makerbase MKS TinyBee?
This board looks good: https://github.com/makerbase-mks/MKS-TinyBee
Best regards
Michael

**Comment by bdring** [comment]
I don't know. You should ask this on the discord server. Others may be familiar with the hardware.

https://discord.gg/chPNNTwv

https://discord.gg/chPNNTwv
