### ISSUE TITLE
what do i need to do with using the mcp4822(spi interface) on the fluidcnc？

### ISSUE THREAD

**Issue by e665107** [bdring/FluidNC#286]
hi，

Now, i want to use the mcp4822(spi interface dac chip) to drive the dac spindle. 
What steps do i need to do? Anyone can help me. Thank you very much。

**Comment by bdring** [comment]
We don't support that chip in FluidNC at this time.

**Comment by e665107** [comment]
Is it very hard for me to adapt the chip to the fluidcnc?

**Comment by e665107** [comment]
I have been working with the embedded software/system for years.  The reason why i watch the fluidcnc is that it is the next edition of esp32_grbl.
I have done some projects with stm32/esp32(esp-idf).

**Comment by e665107** [comment]
Two choices, one is use the esp-idf , and i will integrate the grbl into it.
The other is use the fluidcnc. I don't  konw which one should i use!

**Comment by MitchBradley** [comment]
Why do you need a DAC?  A PWM interface can be used as a DAC with a little filtering.

**Comment by e665107** [comment]
The stepper servo used need in+ and in- signal(5v). Thus,  I need  a DAC.

**Comment by MitchBradley** [comment]
Which servo?

**Comment by bdring** [comment]
I have some of those Galvos. FluidNC is not the way to control them unless you want a slow moving cat toy.

Try using XYScope.

https://teddavis.org/xyscope/

**Comment by e665107** [comment]
Galvos doesn't need the grbl lib? Right?

**Comment by e665107** [comment]
My aim is to implement a laser printer not a laser show, with Galvos. In this situation,  it needs a grbl.

**Comment by bdring** [comment]
I don't have time to add this to FluidNC or even support you with help on it. Here are my suggestions.

- I would start with an ESP32 PWM to experiment with. 
- Run it through a [circuit like this one](https://www.buildlog.net/blog/2018/02/laser-galvo-control-experiments/) to make it the right voltage.
- Create new motor class that overrides the step function to set the PWM level
- Find a very good and close friend who understands electronics and FluidNC who is will to answer your questions.

**Comment by e665107** [comment]
Thank you very much.  My pcb board is ok now, my next work is to implement the software. I have get stuck in using fluidnc or using the esp-idf to move the grbl into it.
