### ISSUE TITLE
Add the Root controller ISO to the hardware list in Wiki

### ISSUE THREAD

**Issue by RootCNC** [bdring/FluidNC#298]
Hi everyone:

I would love to get the Root controller placed on the wiki among the other CNC controllers that are available (if this is OK of course) 

Open Source: [Yes](https://github.com/RootCNC/Root-Controller-ISO)
Project Supporter: No (Not yet anyway!)
For Sale: [Yes](https://rootcnc.com/product-category/electronics/)
Description: Fully isolated 6 Axis motion controller specifically design to drive external stepper motor drivers. includes isolated inputs (x10), USB, RS485, MOSFETs Output (x3), Relay outputs (x3) and a non isolated Laser port. SD card. 

Image Link: https://github.com/RootCNC/Root-Controller-ISO/blob/master/Media/RootControllerISO-R2.0.jpg

Thanks in advance - keep up the great work!

**Comment by bdring** [comment]
Done

https://github.com/bdring/FluidNC/wiki/Hardware-that-Runs-FluidNC#root-controller
