### ISSUE TITLE
Can't connect to Fysetc E4 using .bat

### ISSUE THREAD

**Issue by ofek256** [bdring/FluidNC#328]
Hi, 
I'm trying to install FluidNC on my Fysetc E4 which currently has grbl32 running.
I can't connect to it and the connection times out:
![image](https://user-images.githubusercontent.com/49280581/156442207-c7e943bf-2f5d-4a1f-bbe5-41487df38020.png)
Ignore COM1 and COM9 - I have no idea why my computer recognizes those, it just does. COM13 is the Fysetc E4.
I tried holding the reset button and releasing while "connecting..." shows up, nothing. Clicked it in the middle of the cycle - also nothing. Unplugged and replugged power - also nothing.
Worth noting - I can connect using UGS, it just doesn't work with the installation .bat files.
Any idea why this might be happening? I'd love some help. 
Thanks!

**Comment by bdring** [comment]
Have you asked Fysetc support yet?

**Comment by ofek256** [comment]
I got it working through my laptop. only difference there might be between the two is that my PC is running windows 11 and laptop windows 10. Might that be the issue?

**Comment by bdring** [comment]
I have heard the Windows 11 driver for the cheap CH340 usb/serial chips might not work with all the pins. You might look for an updated driver.

**Comment by bdring** [comment]
I added a note about this to the troubleshooting section of the wiki.

Closing.
