### ISSUE TITLE
Buffers, maximum speed, dpi

### ISSUE THREAD

**Issue by frank8500** [bdring/FluidNC#329]
Fluid 3.4.1
starting data :
laser c02
mks dlc32 , drv8825 , (1/4 microstepper )
laser :
enabled pin ......................... L power supply laser ( inversor transistor )
frecuency pin ..................... IN power supply laser
lightburn .. usb
raster : 508 dpi
tidy plot
velocity : 90 mm/s
I have wifi and bt disconnected

Planner.h
BLOCK_BUFFER_SIZE = 250
Config.h
#define RX_BUFFER_SIZE 8192 // ( 1-254 )
#define TX_BUFFER_SIZE 8192 // ( 1-254 )
BAUD_RATE = 921600;

Looking to find the maximum speed for laser engraving, I found that the following configurations significantly improve the system
In these conditions there is no variation of speed, nor delay of the shots.

If I increase the speed to 100mm/s, a decrease in speed is observed during the raster.

the serial port is not the bottleneck.
increasing the transmit/receive buffers does not improve the situation

modifying these values
const int REPORT_OVR_REFRESH_BUSY_COUNT = 20;  //20 (1-255)
const int REPORT_OVR_REFRESH_IDLE_COUNT = 10;  //10 (1-255) Must be less than or equal to the busy count
const int REPORT_WCO_REFRESH_BUSY_COUNT = 30;  //30 (2-255)
const int REPORT_WCO_REFRESH_IDLE_COUNT = 10;  //10 (2-255) Must be less than or equal to the busy count
const int ACCELERATION_TICKS_PER_SECOND = 100;
does not improve the situation.

increasing the value of block_buffer size , beyond 255 , gives a compilation error

Would it be possible to further increase the value of block_buffer?

config.h
const int SUPPORT_TASK_CORE = 1;  // Reference: CONFIG_ARDUINO_RUNNING_CORE = 1
does it mean that only one core of the micro is used?

Could any other parameter be modified to be able to go further in speed, or are we at the limit of the microcontroller?

On the other hand, I am not clear about the difference between the values.

  disable_with_s0: true/false
  s0_with_disable: true/false

**archive yaml**
board: MKS DLC32 2.0
name: MKS DLC32 FRA
meta: (01/03/2022) Fran j
stepping:
  engine: I2S_STREAM
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: i2so.0
  x:
    steps_per_mm: 25
    max_rate_mm_per_min: 60000
    acceleration_mm_per_sec2: 3000.000
    max_travel_mm: 5000.000
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 5.000

    motor0:
      limit_neg_pin: gpio.36
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      stepstick:
        step_pin:  i2so.1
        direction_pin: I2SO.2

  y:
    steps_per_mm: 25
    max_rate_mm_per_min: 60000
    acceleration_mm_per_sec2: 3000.000
    max_travel_mm: 5000
    soft_limits: false
    homing:
      cycle: 3
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6

  z:
    steps_per_mm: 39
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 50.000
    max_travel_mm: 300.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 800.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm:1.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4

i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.39
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: NO_PIN

probe:
  pin: NO_PIN
  check_mode_start: false

start:
  must_home: false

laser:
  spinup_ms: 1000
  spindown_ms: 1000
  tool_num: 0
  pwm_hz: 20000
  output_pin: gpio.32
  enable_pin: gpio.22
  disable_with_s0: true
  s0_with_disable: false
  
  speed_map: 0=0.000% 1000=100.000%

  coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

thank you very much

**Comment by MitchBradley** [comment]
Did you see continued increases in speed as BLOCK_BUFFER_SIZE increased, or did it max out at some point?

**Comment by Ams-Laser** [comment]
> Did you see continued increases in speed as BLOCK_BUFFER_SIZE increased, or did it max out at some point?
> 

Mitch, i have tested today a similar setup im using 

planear blocks 100
MÁX SPEED X 36000
ACELLERATION 2500

And i can engrave tres hold images at 600mm/s
However stucki does max out at 200mm/s as it begins stutering motions
I Will increase planner blox to max 255 and se if it helps
Will reporte back

**Comment by Ams-Laser** [comment]
seems like max value for planner blocks is 120, can someone please confirm ?

**Comment by Ams-Laser** [comment]
this is my config, good results upto 300mm/s for treshold but only 100mm/s for jarvis,stuki, etc

planner_blocks: 200

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 20
    max_rate_mm_per_min: 36000
    acceleration_mm_per_sec2: 2500
    max_travel_mm: 2450
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 16000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.36:high
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2:high

  y:
    steps_per_mm: 20
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 800
    max_travel_mm: 1850
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 500.000
      seek_mm_per_min: 16000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.35:high
      hard_limits: false
      pulloff_mm: 2.000
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:low
 
  z:
    steps_per_mm: 32
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 10000
    soft_limits: false
    homing:
      cycle: 0
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 200.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: gpio.34:high
      hard_limits: false
      pulloff_mm: 1.000
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low
        
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: NO_PIN
#  card_detect_pin: gpio.39
  
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

#probe:
#  pin: gpio.22
#  check_mode_start: true

Laser:
  pwm_hz: 1000
  output_pin: gpio.32
  disable_with_s0: true
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
#PWM:
#  direction_pin: NO_PIN
#  spinup_ms: 1
#  spindown_ms: 1
  
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  #Beeper connector. Command: "M62 P0" turn beeper On. 
  #"G4 P0.5" wait for 0.5s. "M63 P0" turn beeper OFF
  digital0_pin: I2SO.7
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

start:
  must_home: false

**Comment by bdring** [comment]
http://wiki.fluidnc.com/en/config/top_level_config_items

Please donate to the FluidNC project!
