### ISSUE TITLE
spiffs.bin missing from Release V3.1.5

### ISSUE THREAD

**Issue by RootCNC** [bdring/FluidNC#33]
The ESPtool that is part of the release cannot find the SPIFFS.bin file as its not included in the download.

What version of the firmware are you using?  V3.1.5
Is the problem repeatable? yes - the solution is to download SPIFFS.Bin from the previous release and add it in the Common folder and that seems to solve the issue.

Resolution - Copy spiffs.bin into the `..\\common\\spiffs.bin` Folder

**Comment by bdring** [comment]
This was fixed via PR #34 and merged to devt. 
It will be included in the next release, which will be done soon.
