### ISSUE TITLE
Wifi Country Code für using channel 11,12 + 13

### ISSUE THREAD

**Issue by Oldie-driver** [bdring/FluidNC#331]
I can connect to my wifi router only, if the channel on the Router ist 10 or less.

So i assume, the most commen range is as default setting, maybe US with channel 1-11 ? Even channel 11 here not work.

My request, a config setting (WebU| config.yaml ) für enable channel 11,12 and 13. This is useful if the router itself selects the channel depending on the load on the 2.4 Ghz band

**Comment by MitjaHenner** [comment]
I'm using channel 11 and have no problem with my MKS TinyBee (using the latest FluidNC version).
