### ISSUE TITLE
Failed to execute script py_rth_multiprocessing

### ISSUE THREAD

**Issue by Althafzahra** [bdring/FluidNC#345]
hello, please help, sir, here I have a problem while installing fluidnc, what is the cause and what is the solution? Thank you
![fluidnc](https://user-images.githubusercontent.com/90569123/159193961-00e8135e-4d4e-40a7-bba7-ca849f4b34e7.JPG)

**Comment by MitchBradley** [comment]
Which version of Windows ?

**Comment by Althafzahra** [comment]
> Which version of Windows ?

I'm using windows 7 64 bit

**Comment by MitchBradley** [comment]
Google found this https://github.com/pyinstaller/pyinstaller/issues/4855#issuecomment-676851508

**Comment by Althafzahra** [comment]
> Google found this [pyinstaller/pyinstaller#4855 (comment)](https://github.com/pyinstaller/pyinstaller/issues/4855#issuecomment-676851508)

I have updated and running but I found another problem as shown in the picture. what should i do sir?

**Comment by Althafzahra** [comment]
> Google found this [pyinstaller/pyinstaller#4855 (comment)](https://github.com/pyinstaller/pyinstaller/issues/4855#issuecomment-676851508)

![fluidnc1](https://user-images.githubusercontent.com/90569123/159640707-a0c8df41-8f73-45fe-b0be-e969cb4a39fb.JPG)

**Comment by MitchBradley** [comment]
Microsoft stopped supporting Windows 7 two years ago so we do not support it either. 

The "esptool" program that we use to install FluidNC comes from Espressif, the maker of ESP32 chips.  Search the web for how to install and use it.  The "esptool.exe" variant that we use only works on modern systems, but the basic "esptool.py" version that depends on a Python language setup will probably work on your system.  I do not have time to teach you how to do that, but there are many tutorials on the web about using esptool.

If you can install Python version 3 and get esptool.py from the web, you can then run these commands in a CMD window to install FluidNC:

```
cd fluidnc-v3.4.2-win64
python esptool.py --chip esp32 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0x1000 common\bootloader_dio_80m.bin 0xe000 common\boot_app0.bin 0x10000 wifi\firmware.bin 0x8000 wifi\partitions.bin
```

The first `cd` command puts you into the fluidnc installer folder.  You might have to add additional path components to get to that folder.

**Comment by Althafzahra** [comment]
> 
Thank you sir for your time and answer, I will try.

**Comment by Althafzahra** [comment]
> Microsoft stopped supporting Windows 7 two years ago so we do not support it either.
> 
> The "esptool" program that we use to install FluidNC comes from Espressif, the maker of ESP32 chips. Search the web for how to install and use it. The "esptool.exe" variant that we use only works on modern systems, but the basic "esptool.py" version that depends on a Python language setup will probably work on your system. I do not have time to teach you how to do that, but there are many tutorials on the web about using esptool.
> 
> If you can install Python version 3 and get esptool.py from the web, you can then run these commands in a CMD window to install FluidNC:
> 
> ```
> cd fluidnc-v3.4.2-win64
> python esptool.py --chip esp32 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0x1000 common\bootloader_dio_80m.bin 0xe000 common\boot_app0.bin 0x10000 wifi\firmware.bin 0x8000 wifi\partitions.bin
> ```
> 
> The first `cd` command puts you into the fluidnc installer folder. You might have to add additional path components to get to that folder.

it's been going well, so far haven't found any problems, thank you very much sir for your help. I have another question, sir, does Webui Fluidnc not work on Android?
![WEBUI](https://user-images.githubusercontent.com/90569123/160031584-5dc245ef-3161-41af-95df-58cb9f1a149f.jpg)
trying on android smartphone having problems
![Screenshot_20220325-071425_Chrome 1](https://user-images.githubusercontent.com/90569123/160031839-a0e32216-791f-449c-9045-8bb76c34a4e6.jpg)

**Comment by Althafzahra** [comment]
> Microsoft stopped supporting Windows 7 two years ago so we do not support it either.
> 
> The "esptool" program that we use to install FluidNC comes from Espressif, the maker of ESP32 chips. Search the web for how to install and use it. The "esptool.exe" variant that we use only works on modern systems, but the basic "esptool.py" version that depends on a Python language setup will probably work on your system. I do not have time to teach you how to do that, but there are many tutorials on the web about using esptool.
> 
> If you can install Python version 3 and get esptool.py from the web, you can then run these commands in a CMD window to install FluidNC:
> 
> ```
> cd fluidnc-v3.4.2-win64
> python esptool.py --chip esp32 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0x1000 common\bootloader_dio_80m.bin 0xe000 common\boot_app0.bin 0x10000 wifi\firmware.bin 0x8000 wifi\partitions.bin
> ```
> 
> The first `cd` command puts you into the fluidnc installer folder. You might have to add additional path components to get to that folder.

it's been going well, so far haven't found any problems, thank you very much sir for your help. I have another question, sir, does Webui Fluidnc not work on Android?
![WEBUI](https://user-images.githubusercontent.com/90569123/160032155-9e20217e-6b4d-452e-b76a-8c2101c2f527.jpg)

trying on android smartphone having problems
![Screenshot_20220325-071425_Chrome](https://user-images.githubusercontent.com/90569123/160032241-12d076ce-feb8-41eb-8285-b755454f080d.jpg)

**Comment by MitchBradley** [comment]
You should configure FluidNC to use an external Wifi setup - STA mode - instead of using AP mode.  AP mode is only good for initial setup.  It has performance problems for real use.

Once you are connected to the external Wifi, you can access FluidNC from your smartphone if it is also connected to the same Wifi.

Refer to this documentation https://github.com/bdring/FluidNC/wiki/FluidNC-Wifi-and-Bluetooth-Setup

**Comment by Althafzahra** [comment]
> You should configure FluidNC to use an external Wifi setup - STA mode - instead of using AP mode. AP mode is only good for initial setup. It has performance problems for real use.
> 
> Once you are connected to the external Wifi, you can access FluidNC from your smartphone if it is also connected to the same Wifi.
> 
> Refer to this documentation https://github.com/bdring/FluidNC/wiki/FluidNC-Wifi-and-Bluetooth-Setup

I've been trying it for a few days and it's working fine.  thank you sir for the help.
