### ISSUE TITLE
Probing set value as negative

### ISSUE THREAD

**Issue by SnowBeaver** [bdring/FluidNC#351]
Please only submit bugs for the **latest** version of the code. You can check the version number in the startup messages.

**Do not add the bug label**. The developers of this repo will do that after confirming the issue.

Please provide the [FluidNC boot messages per this page](https://github.com/bdring/FluidNC/wiki/Requesting-Help#fluidnc-boot-messages).

Please answer the following questions.

What version of the firmware are you using?
3.4.2

Is the problem repeatable?
Yes

Under what conditions does the bug occur?
Probing

**Important** If you paste firmware code, please use [Markdown Code and Syntax Highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with language C++. Use the three back tick method.

```C++
  #define EASIER_TO_READ true
```
I use the following macro to initiate a probing action on Z axis: G38.2 G91 F80 Z-20 P10.00. I also tried G38.2 F80 Z-20 P10.00 with same results.
Probing completes successfully with following message: [PRB:97.004,97.004,4.517:1]
However, a -10.0 is been assign to the Z axis and displayed in the webui jog panel where it should be +10.00

[Startup-message.txt](https://github.com/bdring/FluidNC/files/8356329/Startup-message.txt)

**Comment by bdring** [comment]
Fixed,

See [PR](https://github.com/bdring/FluidNC/pull/352)

**Comment by SnowBeaver** [comment]
Thanks
