### ISSUE TITLE
SDCard.cpp _cardDetect.setAttr(Pin::Attr::Output);

### ISSUE THREAD

**Issue by klaus-liebler** [bdring/FluidNC#362]
Hi FluidNC-Team,

thank you for this great piece of software!

I think, the "cardDetect" pin only needs input capability --> see SDCard.cpp, line 102. 
After having changed this, the card_detect pin for board MKS_DLC32 can be set to "gpio.39:low".

Regards,

Klaus

**Comment by kjk25** [comment]
same for my installation MKS DLC32 V2.1

**Comment by MitchBradley** [comment]
Fixed by #375 .  Will appear in the next release.
