### ISSUE TITLE
x modem missing on wifi.bat 3.4.3 version

### ISSUE THREAD

**Issue by kweilim98** [bdring/FluidNC#379]
Does anybody has try with the wifi.bat on the 3.4.3 version after uploading needed the window PowerShell to get the wifi password so only can access to the webui? because i cant reach there, the program show x modem missing and no definite.

**Comment by MitchBradley** [comment]
Show us exactly what you did with screenshots.  We cannot understand what you wrote.

**Comment by kweilim98** [comment]
![image](https://user-images.githubusercontent.com/66898187/163330860-886ea8a1-7e02-4c43-8960-2a69d1086067.png)

**Comment by bdring** [comment]
On Windows, it is easier to use fluidterm.exe, than fluidterm.py.

**Comment by MitchBradley** [comment]
There is no file named "wifi.bat" in fluidnc-v3.4.3-win64.zip .  The closest file to that name is "install-wifi.bat".  install-wifi.bat uses fluidterm.exe which does not use the Python code that you show above.  From the information that you have provided, we cannot determine how you got to that Python code.  The screenshot that you provided shows us an excerpt from the fluidterm.py file, but it does not show us what you did to try and run that file.  It should not be necessary to use fluidterm.py on a Windows system.
