### ISSUE TITLE
WiFi password

### ISSUE THREAD

**Issue by kweilim98** [bdring/FluidNC#390]
Where can I get the password WiFi for fluid NC
![WhatsApp Image 2022-04-18 at 12 57 34 PM](https://user-images.githubusercontent.com/66898187/163757154-9baa6f2b-b49c-4f82-b7fe-d29533a3ea3e.jpeg)
![WhatsApp Image 2022-04-18 at 12 57 34 PM (1)](https://user-images.githubusercontent.com/66898187/163757178-ba80f839-2797-4bab-83b0-820c4f7e2b76.jpeg)
?

**Comment by Avataar120** [comment]
Hello,
In the wiki

https://github.com/bdring/FluidNC/wiki/FluidNC-Wifi-and-Bluetooth-Setup

Default password is 12345678
