### ISSUE TITLE
Mechanical error compensation

### ISSUE THREAD

**Issue by dzario** [bdring/FluidNC#405]
Hi.
I build my own CNC from polymer concrete
[Photo](https://photos.app.goo.gl/dBbXsZs1QvK7enkS8)
and I have some mechanical error , search CNC control
system for software compensation.
Is possible do it with FluidNC ?
3D printer marlin have Skew compensation .. Any idea?

**Comment by bdring** [comment]
We only have auto squaring for dual motor axes.

I don't know what you mean by skew. Your link is broken. Is the machine like a non right angle parallelogram? Some compensation might be possible via kinematics, but you would need to write that yourself.

**Comment by dzario** [comment]
Hi. Sorry ,now link working .
Yes, parallel , right angle etc .
Marlin have skew function .

**Comment by bdring** [comment]
Use Marlin then.
