### ISSUE TITLE
Onboard reset boot error with TMC2209 - ESPDuino32

### ISSUE THREAD

**Issue by TinkerBoi** [bdring/FluidNC#421]
Hello!

I'm running an ESPDuino32 board with the CNC Shield V3 found [here](https://github.com/bdring/Grbl_Esp32/issues/369#issue-593745142). I swapped out the DVR8825 for TMC2209 driver, everything seems to run fine except when I hit the soft reset on the board I get a boot error, my only option is to cut the power, unplug usb and reconnect which isn't always practical. I understand that there are some mismatched in this setup but if there is a way to run the 2209 in standardlone mode, I'd be happy.

rst:0x10 (rtcwdt_rtc_reset),oot:0x22 (download_boot(uart0/art1/sdio_rei_feo_v2)) waiting for download

There are two things I'm not certain about - 

1. Are my TX/RX pins configured correctly for this setup? 
2. I think it's running in legacy mode as changing the steps in the config file didn't make any difference (but jumpers on the board did). 

If I leave the UART pins (NC, TX, RX) unconnected (as direct replacement of 8825), it throw this error on pressing the reset:

rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371

Settings:

[config.txt](https://github.com/bdring/FluidNC/files/8693505/config.txt)

Boot message:

[VER:3.4 FluidNC v3.4.4:]
[OPT:PHS]
[MSG: Machine: MACHINE_ESPDUINO_32]
[MSG: Mode=STA:SSID=:Status=Not connected:IP=0.0.0.0:MAC=0C-B8-15-C3-60-64]
[MSG:Mode=AP:SSDI=LP1224-Laser:IP=192.168.0.1:MAC=0C-B8-15-C3-60-65Mode=AP:SSDI=LP1224-Laser:IP=192.168.0.1:MAC=0C-B8-15-C3-60-65]

This is the boot error when I hit the reset (with the CNC shield still powered)

rst:0x1 (POWERON_RESE)boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_dv:0x00,cs0_drv:0x00,hd_drv:00,wp_drv:0x00
mode:DIO, clock div:1
load03fff0018,len:4
load:0x3ff001c,len:1044
loa:0x40078000,len:10124
la:0x40080400,len:5856
ntry 0x400806a8

rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff007a,len:-444644243
1162 mmu set 00010000, pos 00010000

rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00

rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371

and then it keep repeating the same (last) error repeatedly

**Comment by MitchBradley** [comment]
Please supply complete config files, not excerpts of the parts that you think are implicated, and also boot messages.  Boot errors are often caused by signal levels on certain gpios. Unless we can see everything, we cannot help you find the problem ones.

**Comment by TinkerBoi** [comment]
> Please supply complete config files, not excerpts of the parts that you think are implicated, and also boot messages. Boot errors are often caused by signal levels on certain gpios. Unless we can see everything, we cannot help you find the problem ones.

Sorry about that Mitch! I update the original post with the full config file and more boot message details.

**Comment by MitchBradley** [comment]
Sometimes GPIO 12 causes boot problems.  Perhaps the new stepsticks affect the signal level on that line during reset.

**Comment by MitchBradley** [comment]
Did you remove the pullup resistor as described in the issue that you linked to?

**Comment by MitchBradley** [comment]
I don't think it is possible to use TMC2209 in UART mode with a Protoneer CNC Shield V3.  According to [these schematics](https://blog.protoneer.co.nz/wp-content/uploads/2013/07/Arduino-CNC-Shield-Schematics.png), the UART pin which is on stepstick pins 13 and 14 not connected back to the Arduino shield pins, so the ESP32 would not be able to drive them.  Therefore, it is probably better to configure them as "stepstick" instead of TMC2209.

The boot problem could be caused by pulldown resistors on the stepstick modules or in the TMC2209 chips themselves.  The TMC2209 datasheet vaguely suggests that the chips might have internal pulldowns on the ENN pin, but does not call it out clearly.  There are two ways to fix that:

1. You could clip the enable pins on the stepsticks, thus disconnecting them from GPIO 12.  The motors would be always enabled then - although you could add a switch to pull up those pins to disable them manually.
2. It is possible to set an efuse in the ESP32 chip to make it ignore the state of GPIO 12.  There is some discussion of that somewhere, but I don't remember where it is.  We do not support that because changing efuses can brick your ESP32 unless you know exactly what you are doing.

**Comment by TinkerBoi** [comment]
> Did you remove the pullup resistor as described in the issue that you linked to?

Yes I did! Everything worked great except for the soft reset.

> I don't think it is possible to use TMC2209 in UART mode with a Protoneer CNC Shield V3. According to [these schematics](https://blog.protoneer.co.nz/wp-content/uploads/2013/07/Arduino-CNC-Shield-Schematics.png), the UART pin which is on stepstick pins 13 and 14 not connected back to the Arduino shield pins, so the ESP32 would not be able to drive them. Therefore, it is probably better to configure them as "stepstick" instead of TMC2209.
> 
> The boot problem could be caused by pulldown resistors on the stepstick modules or in the TMC2209 chips themselves. The TMC2209 datasheet vaguely suggests that the chips might have internal pulldowns on the ENN pin, but does not call it out clearly. There are two ways to fix that:
> 
> 1. You could clip the enable pins on the stepsticks, thus disconnecting them from GPIO 12.  The motors would be always enabled then - although you could add a switch to pull up those pins to disable them manually.
> 2. It is possible to set an efuse in the ESP32 chip to make it ignore the state of GPIO 12.  There is some discussion of that somewhere, but I don't remember where it is.  We do not support that because changing efuses can brick your ESP32 unless you know exactly what you are doing.

Thank you so much for the suggestions! I'm fine to run it in stepstick  mode, I wasn't sure if my config was correct?

Let me try with the EN disconnected, I'll report back.

**Comment by bdring** [comment]
We have that controller listed under the [Do Not Use](https://github.com/bdring/FluidNC/wiki/Hardware-that-Runs-FluidNC#do-not-use) section of the wiki.

Yes, some people have managed to make it work, but please don't expect us to answer support questions on literally the cheapest CNC controller in the world.

**Comment by TinkerBoi** [comment]
> We have that controller listed under the [Do Not Use](https://github.com/bdring/FluidNC/wiki/Hardware-that-Runs-FluidNC#do-not-use) section of the wiki.
> 
> Yes, some people have managed to make it work, but please don't expect us to answer support questions on literally the cheapest CNC controller in the world.

I apologize as I didn't mean to come off wrong or have any expectation to get any help for this issue, and this issue I could easily live with by power cycle option as I mentioned above. I know its literally the cheapest but its the only option I have on hand to work with. I was actually looking to buy your V4 controller with 3 axis and I kept checking back but they're sold out so im left with this option. If you have any of those board on hand (even used or prototype), I'd love to get one to replace this problematic setup.

Appreciated Mitch and your help very much!
