### ISSUE TITLE
Using TMC2209 Driver in standalone mode?

### ISSUE THREAD

**Issue by TinkerBoi** [bdring/FluidNC#422]
Is it possible to configured the TMC2209 driver to be used in standalone with only DIR/STEP, and EN shared pins as a direct replacement for 4988 or 8825 without the UART? I didn't find any information in the wiki guide or may be I did miss something? Thank you.

**Comment by bdring** [comment]
Standalone mode means stepstick mode. We have a [section for that](https://github.com/bdring/FluidNC/wiki/FluidNC-Motor-Setup#stepstick).

Please ask the maker of the driver for instructions on how to put it in StepStick mode.

**Comment by TinkerBoi** [comment]
Thank you! I was a bit confused on the terminology.
