### ISSUE TITLE
Y axis reversed in Webui, how to change direction?

### ISSUE THREAD

**Issue by TinkerBoi** [bdring/FluidNC#423]
Is there anyway I can switch direction of the arrow keys panel in the WebUI? For some reason when I press up it goes down and vice versa on my Y axis but my X direction is correct. However, in Lightburn and LaserGRBL both axises run in the correct direction.

**Comment by breiler** [comment]
Read about `direction_pin` here for reversing stepper motor driver:
https://github.com/bdring/FluidNC/wiki/FluidNC-Motor-Setup#standard_stepper
