### ISSUE TITLE
TMC5160

### ISSUE THREAD

**Issue by boucz** [bdring/FluidNC#45]
Hi
Is the bug with grbl-esp32 and TMC5160 still present in FluidNC? I would like to use stealthchop but with higher Amps than allowed with TMC2130. (I do not have the drivers for now)
Thanks !

**Comment by bdring** [comment]
I assume so, but there may be  few things we could try to fix it in FluidNC. I could create a test branch with the changes, but there is no guarantee it will be fixed.

**Comment by boucz** [comment]
Motors (random position) stops working but the gcode continue.
First time it was the x axes, the second time with lower current the y axis stops during running the same gcode (spindle running without bit speed and acceleration very conservative)

**Comment by bdring** [comment]
It might be a problem we cannot fix in firmware.

**Comment by boucz** [comment]
maybe, i'll run it with my tmc2130 to be sure.

**Comment by atlaste** [comment]
Can you please double and triple-check that you have the right branch? https://github.com/bdring/FluidNC/tree/Trinamic is the right one, not to be confused with the TMCsomething branch. You can spot it in the TrinamicSPI class with all the if's if you look for 5160 and 2130. The boot message of Fluidnc should also dump the version with the git tag.
