### ISSUE TITLE
Question about the start of operation of the designated line after the power failure in the middle?

### ISSUE THREAD

**Issue by yangyi-sz** [bdring/FluidNC#478]
### Controller Board

Hello, I am an amateur from China. I am currently using MKS DLC32, a 6-axis cnc control board, and found a very fatal problem. How can we start the execution of the specified line after the cnc device stops halfway? And how to retrieve the workpiece coordinate value after power off, my equipment uses mechanical limit switch.

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [X] Not Applicable

### Machine Description

MKS DLC32, a 6-axis cnc

### Configuration file

```yaml
MKS DLC32, a 6-axis
```

### Startup Messages

```text
$SS < $Sta/SSID=GRBL_ESP
$Sta/Password=******
$AP/SSID=GRBL_ESP
$AP/Password=******
$Message/Level=Info
```

### User Interface Software

candle

### What happened?

中途断电以后，重新上电出现的问题

**Comment by MitchBradley** [comment]
FluidNC does not have the capability to restart a job that was interrupted by power off.  The coordinates cannot be retrieved.

We do not have plans to add such a feature.  It is very complicated to do that correctly with inexpensive hardware.  One way to do it with external hardware would be to power the controller from a battery-backed uninterruptible power supply (UPS) and connect the UPS's power-fail signal to a feedhold input on the controller.  That way, if external power is lost, the controller would pause the job, hopefully before the spindle stopped spinning.  The UPS would retain power to the controller for some amount of time, hopefully long enough for you to write down the coordinates and the GCode line.  If power is restored before the UPS runs out of battery power, you might be able to resume the paused job.
