### ISSUE TITLE
FluidNC & MKS DLC32 / MPCNC v1.2.2

### ISSUE THREAD

**Issue by IgorPack** [bdring/FluidNC#510]
### Machine Context

Milling machine: X/Y1,Y2/Z, T8, NEMA23 1.2H.M 2.8A, TMS2209 v1.2

### Feature Description

Hi,
Since I can't create messages on Discord, I want to ask here. I want to try to use MKS DLC32 or MPCNC Controller v1.2.2 together with FluidNC for a milling machine (X/Y1,Y2/Z, T8, NEMA23 1.2H.M 2.8A, TMS2209 v1.2). If someone can share an example config.yaml for this or a similar machine, as well as recommendations for setting it up, I would be very grateful for the help. 
Thanks.

### Other Approaches

Haven't tried yet

### How I Can Help

I can help you with testing.

**Comment by MitchBradley** [comment]
There are several example config files for both boards in https://github.com/bdring/FluidNC/tree/main/example_configs

There are also quite a lot of auto-translated configs for MPCNC -  https://github.com/bdring/Grbl_Esp32/search?q=MPCNC&type=issues .

Please search before asking questions.  GitHub search in the FluidNC and Grbl_Esp32 repositories turns up many hits for MPCNC and DLC32.  You can search the code, issues, wiki, ...

![image](https://user-images.githubusercontent.com/4861133/175605788-52d2a075-a62c-4515-9c39-0e210a28e201.png)

**Comment by IgorPack** [comment]
Thank you so much for your comment, Mitch. I saw these files, I just wanted to save myself time and get the opinion of those who use them. Good luck.
