### ISSUE TITLE
WebUI upgrade to V3

### ISSUE THREAD

**Issue by mathojojo** [bdring/FluidNC#560]
### Machine Context

FluidNC seems to have an old implementation of WebUI. The V3 version of WebUI is out, and FluidNC could benefit from this new interface.

### Feature Description

[https://github.com/luc-github/ESP3D-WEBUI/blob/3.0/Features.md](https://github.com/luc-github/ESP3D-WEBUI/blob/3.0/Features.md)
![GRBL WebUI v3](https://user-images.githubusercontent.com/16633360/183285956-b62e6a3d-5dda-448e-923d-dbae7c610ffa.png)

### Other Approaches

_

### How I Can Help

I'm not sure I can help, I'm not programmer.
But I hope it is easy to do (maybe just replacing files from old version with the new files ??)

**Comment by MitchBradley** [comment]
It has been on our list for awhile.  It is not as easy as replacing the files because there were some protocol changes.  We could use a programmer to help with this because we have a lot of other stuff to do.
