### ISSUE TITLE
BLE does not work！！

### ISSUE THREAD

**Issue by chenzhenyun** [bdring/FluidNC#565]
### Controller Board

3-PACK

### Help From Board Vendor

- [ ] Yes
- [ ] No
- [ ] Not Applicable

### Machine Description

NONE

### Configuration file

```yaml
NONE
```

### Startup Messages

```text
NONE
```

### What happened?

I tried to connect my machine with iPhone Bluetooth, but I couldn't find the interface. Does it not support BLE connection?

**Comment by MitchBradley** [comment]
No, FluidNC does not support BLE.  It supports Bluetooth Serial.
