### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by ashokavarthanan** [bdring/FluidNC#572]
### Machine Context

My CNC machine. ESP32-GRBL
x100mm-y200mm-z75mm
1.5kw Spindle.

### Feature Description

Hi, 
I am using  FluidNC from last month, its nice.
I want to save "Machine position (x y z) " for last 10 history 
when "SET COORDINATE ZERO" into ESP32 memory.
(with time if possible)

Example:
1.2022-08-17 20:11:00 M=X10.500Y15.600Z-1.100 W=X0Y0Z0
2.2022-08-17 21:20:00 M=X20.500Y15.600Z5.000 W=X0Y0Z0
Thanks.

### Other Approaches

nothing.

### How I Can Help

nothing.

**Comment by bdring** [comment]
That is not supported by standard gcode.

In my opinion a PC based gcode sender would be a better place. It would have access to time and more storage.

**Comment by ashokavarthanan** [comment]
10 lines of CODE takes 525-bytes (around 45 kilobytes free in ESP32 ).
I think its enough.
and 
when SET COORDINATE G-code execute  "G10 L20 P1"
if g-code "G10 L20 P1" execute  can save line? (Current Machine position)
Thanks.

**Comment by bdring** [comment]
Then what?

How is that value returned to the user? 
What does the user do with it? 
How is it applied to the machine?
Where does time come from?
How do existing senders deal with it?

A PC sender would do a better job of this.

**Comment by ashokavarthanan** [comment]
its More helpful for re-position when power cuts.

**Comment by bdring** [comment]
The value is already stored in G54-G59

**Comment by ashokavarthanan** [comment]
I understand...  The value is stored.
But when is test Manual Power cut and re-connect ESP 
the Machine value all 0
???

**Comment by bdring** [comment]
Regardless of what we do, you must rehome, then the G54 offset is correct.

**Comment by ashokavarthanan** [comment]
I am not familiar with G54 G-code.
I start machine every time with rehome.
But when power failure( or Hang or any Error and issue ) more time I loss  Machine position.
This way more Helpful.
Anyway Thanks for Answer.

**Comment by MitchBradley** [comment]
Loss of machine position on power fail is unavoidable since the motors lose their lock and and mechanical stresses that have accumulated are released.

**Comment by bdring** [comment]
You have a lot to learn about machine positions. Watch this video. It will likely solve your problem.

https://www.youtube.com/watch?v=fGtbkVJBXyE&
