### ISSUE TITLE
Feature: Add Support for the W5500 SPI Ethernet Module

### ISSUE THREAD

**Issue by gxdeange** [bdring/FluidNC#655]
### Machine Context

I am building a custome board that supports 6 channel (I2S) and would like to see if the firmware can support SPI Ethernet (W5500)

### Feature Description

Spi Ertyhernet module support

### Other Approaches

I have not tried any other approach as I do not know how to code

### How I Can Help

I could provide a donation to purchase the ethernet module however they go for a few dollars on AliExpress

**Comment by MitchBradley** [comment]
I have used W5500 on ESP8266 so I have a basic idea of how to connect it to the ESP framework. I'm not sure that we want to support it for FluidNC because there are few if any other potential users.  Adding it would require documentation, testing, and support.

**Comment by gxdeange** [comment]
Ok. No problem.

Thanks again for looking at this request and responding.

Cheers and have a great day
