### ISSUE TITLE
Feature: use the same GPIO in all axes to homing.   -  limit_neg_pin: gpio.xx

### ISSUE THREAD

**Issue by RDS356** [bdring/FluidNC#675]
### Machine Context

Simplifying the wiring.

### Feature Description

Like on grbl 0.9, mach3, etc you can use the same pin to all axes to make the homing. Using all switch in mode NC and in serie.
But in fluidnc a message error come  when you try and not work. 
Is there a way to make it possible  ?
Regards,
Reinaldo de Souza

### Other Approaches

Let the user use same pin in config.yaml files.

### How I Can Help

.

**Comment by bdring** [comment]
You can use the `limit_all_pin:` to put a switch at both ends of an axis on the same I/O pin. You cannot use the same input for more than one axis. 

We probably do not want to add a feature for that. It would be too hard to support and debug problems.
