### ISSUE TITLE
TMC2209 & SpreadCycle & Interpolation

### ISSUE THREAD

**Issue by cranefist** [bdring/FluidNC#698]
How do i set the following settings for TMC2209:

```
0 microstepping
Interpolation true
SpreadCycle
```

There does not seem to exists SpreadCycle in the mode selection?
And if i set microstepping to 0 it does not like it.
Cant find anything about interpolation setting at all?

These settings optimize torque from my nema17 motors. SpreadCycle offers higher torque than StealthChop, and having 0 microstepping gives the highest torque output, while interpolation smooths the movements and reduces motor noise when using 0 microstepping.

As my leadscrews have 1mm lead, 200/mm steps is more than enough for my purposes.

**Comment by bdring** [comment]
We are not experts on  the chip. We just have some basic settings to config some modes. Some modes like Spreadcycle can be a combination of register settings.

The lowest microstep setting is 1 (1:1 no extra steps)
I think the default for interpolation is on.

![image](https://user-images.githubusercontent.com/189677/201188515-15fe44b8-7ed7-4555-b68f-0790f374fc78.png)

Can you tell me the exact setting to the register values that you want?

**Comment by cranefist** [comment]
Ok, so interpolation defaults on. I think you want to make that into a setting, because it also apparently has negatives. At least klipper documentations says that it can introduce some tiny delay. But its really good for full stepping.

![image](https://user-images.githubusercontent.com/35430692/201225422-e1300962-ba6f-4f25-b04f-e3083558c138.png)

Setting this as 1 puts it into SpreadCycle, it would be good as some motors simply do not like StealthChop and there is also considerable more torque in SpreadCycle.

I will try setting microstepping as 1, it the register it should be set as 0 for no microstepping. So 0 equals 1:1.

**Comment by hasankarainfo** [comment]
I made a change to the spreadcycle property and it works with tmc2208 stepper drivers. I could observe that the maximum rotation speed increased by 2.5 times compared to all other modes. As expected, some hissing sounds. 

 [https://www.klipper3d.org/TMC_Drivers.html?h=stealth ](url) When I read some of the explanations in this link, I especially wanted to see the effect of spreadcycle mode on the results in sensitive tasks. In my opinion, many users may want to see the effect of this feature on the result. I have updated a total of 3 lines in two different files. I can expect these changes to be reviewed by project managers and to inform the community if there will be negative consequences.

[https://vscode.dev/github/bdring/FluidNC/blob/main/FluidNC/src/Motors/TMC2208Driver.cpp?vscode-lang=tr#L57](url) 
Modify `tmc2208->en_spreadCycle(_en_spreadCycle);`

[https://vscode.dev/github/bdring/FluidNC/blob/main/FluidNC/src/Motors/TrinamicBase.h?vscode-lang=tr#L48](url)
Put `bool _en_spreadCycle        = true;`

[https://vscode.dev/github/bdring/FluidNC/blob/main/FluidNC/src/Motors/TrinamicBase.h#L85](url)
Put `
            handler.item("en_spreadCycle", _en_spreadCycle);`
Using the "firmware settings" interface, I can update en_spreadCycle and see its effect on the result.

Other details;

Uart addressing cannot be used in tmc2208 drivers, so the address of all of them must be set to 0. 
As hardware, I use 3x tmc2208, esp32 4mb. 
![Image](https://github.com/user-attachments/assets/b4f82843-ec9a-4069-bc2c-03b0103b8a99)
In this scenario, the firmware sends the same parameters as all 3 drives. It only reads the data of the drive designated as master. As a result, the same parameters are set for all stepper drivers.


I am sharing the config.yaml I use in the attachment. 

[config.yaml.zip](https://github.com/user-attachments/files/18548826/config.yaml.zip)
