### ISSUE TITLE
Problem: tying to update firmware via OTA "not enough space error"

### ISSUE THREAD

**Issue by mac7988** [bdring/FluidNC#717]
### Controller Board

6-pack

### Machine Description

custom

### Input Circuits

```yaml
custom
```

### Configuration file

```yaml
custom
```

### Startup Messages

```text
NA
```

### What happened?

using WIFI.ELF give not enough space error

**Comment by bdring** [comment]
You should be uploading a .bin file.

**Comment by bdring** [comment]
http://wiki.fluidnc.com/en/installation#over-the-air-ota-updates

**Comment by mac7988** [comment]
ah, silly mistake. Sorry about that
