### ISSUE TITLE
Problem: I am getting an error for Fluid Term when I try to open. "setConsoleColor failed"

### ISSUE THREAD

**Issue by DanAttema** [bdring/FluidNC#740]
### Controller Board

ESP32 WROOM board.  Downloaded FluidNC fine.

### Machine Description

Using an ESP32 to control an XYYZ CNC Gantry Router.  

### Input Circuits

```yaml
None yet.  Just starting.
```

### Configuration file

```yaml
None yet.  Will be an XYYZ.
```

### Startup Messages

```text
Have got that far.
```

### User Interface Software

FluidTerm

### What happened?

I am getting an error for Fluid Term when I try to open. "setConsoleColor failed" The next line is "...press any key to continue".  It exits when I press a key.  Multiple attempt produce the same result.  It looks like a problem with Python or Windows or something.  Any suggestion will be helpful.

I am going to try another terminal program.

### Other Information

Screen shot FluidTerm error.

![image](https://user-images.githubusercontent.com/120130421/206542643-ca54b576-5c65-4b33-b161-e4c1e7dffdaa.png)

**Comment by DanAttema** [comment]
Startup Messages

Should say "Have not got that far."

**Comment by MitchBradley** [comment]
Ancient version of Windows?

**Comment by DanAttema** [comment]
Windows 7

**Comment by MitchBradley** [comment]
So yes.  Windows 7 does not have the new console subsystem.  Can you use a different machine?

**Comment by DanAttema** [comment]
Not conveniently.  Does Windows 10 work?  What would be an alternative terminal program to run on Windows 7?

**Comment by MitchBradley** [comment]
win 10 works just fine, especially if it is reasonably up to date, like say within the last year or so.  Any terminal program will work; I like PuTTY and TeraTermPro.

**Comment by MitchBradley** [comment]
Arduino serial monitor works too.

**Comment by DanAttema** [comment]
Thanks for the help and the quick response.  I may upgrade my computer to Windows 10.  For now I will try one of the alternatives.

**Comment by MitchBradley** [comment]
I would not recommend upgrading a Windows 7 machine to windows 10.  Old machines often have problems with new operating systems.

**Comment by MitchBradley** [comment]
windows 10 laptops go for about $100 on ebay

**Comment by DanAttema** [comment]
A cheep laptop could work for FluidTerm.  

When I bought this machine it came with Window 10 upgrade as an option.  I installed Window 7 because I was running some legacy programs at the time.  Kind of regretting it now as Windows 10 is needed many new programs.

**Comment by MitchBradley** [comment]
FluidTerm is not necessary.  It has some nice features for our internal uses, and it is a known starting point so we don't have to tell people how to set up half a dozen other serial terminals, but other serial terminals will do the job, and for long-term use you will want to use either WebUI or a sender like UGS.
