### ISSUE TITLE
Problem:  the job pauses for 5-15 seconds like its a video buffering.

### ISSUE THREAD

**Issue by CesarHaroldoArias** [bdring/FluidNC#749]
### Controller Board

6-pack

### Machine Description

Lowrider V2 cnc 

### Configuration file

```yaml
cant access the webui during the job
```

### Startup Messages

```text
cant access the webui during the job
```

### User Interface Software

webui

### What happened?

sended the gcode and hit the PLAY button on the webUI, the file is running but it pauses a lot every 10-30 secs like its buffering

**Comment by MitchBradley** [comment]
Reopen a ticket with the required information when you can.  We really really need it before we can help you and having it in the correct place will make things easier for us.
