### ISSUE TITLE
Problem: config parameter documentation outdated

### ISSUE THREAD

**Issue by kdomanski** [bdring/FluidNC#761]
### Controller Board

irrelevant

### Machine Description

irrelevant

### Configuration file

```yaml
irrelevant
```

### Startup Messages

```text
irrelevant
```

### What happened?

Both the old and the new wiki claim the the hostname is configured with `$System/Hostname` parameter. This has been renamed to `$Hostname` in [this commit](https://github.com/bdring/FluidNC/commit/0c18659f0e31720a84212befe09f9a5c3b2eee37#diff-eb8b6a7ecbf5d776abc79d56eedb5193e31a4165f793c765dd6973a7f3e9b013L1038).

**Comment by MitchBradley** [comment]
Fixed, thanks for noticing it.
