### ISSUE TITLE
Web UI on widescreen, G20 features misaligned

### ISSUE THREAD

**Issue by maxcel2** [bdring/FluidNC#779]
### Controller Board

N/a

### Machine Description

N/a

### Configuration file

```yaml
N/a
```

### Startup Messages

```text
N/a
```

### User Interface Software

WebUI

### What happened?

When the WebUI, Tablet tab, is viewed on a wide screen, the buttons/boxes in the G20 panel are all out of position and don't make any logical sense. If the width of the window is progressively reduced, the buttons start to compact to logical positions. There appears to be an optimum screen x resolution for the x, y & z to be in the correct positions, but then the text in other buttons is truncated.

**Comment by MitchBradley** [comment]
What is the "G20 panel".  I see no panel with that name or label.

**Comment by bdring** [comment]
Closing stale, incomplete issue
