### ISSUE TITLE
Documentation broken link in getting started.

### ISSUE THREAD

**Issue by iplayfast** [bdring/FluidNC#789]
### Controller Board

Using the getting started wiki, The line 
You need to create and upload a [config file](http://wiki.fluidnc.com/config/config_overview) to tailor the firmware to your machine.

[config file] should be pointing to http://wiki.fluidnc.com/en/config/overview

As this is in the getting started section, I thought it was important.

### Machine Description

n/a

### Input Circuits

```yaml
n/a
```

### Configuration file

```yaml
n/a
```

### Startup Messages

```text
n/a
```

### User Interface Software

n/a

### What happened?

n/a

**Comment by bdring** [comment]
Thanks...fixed
