### ISSUE TITLE
Feature: Wemos d1 r32    esp32 board "arduino uno footprint". 

### ISSUE THREAD

**Issue by berin-aquaquad** [bdring/FluidNC#793]
### Machine Context

I would love to see this project compiled for the Wemos D1 R32 board. Being that it is an Arduino uno footprint. The quad stepping motor controller HAT for the uno board. would be amazing to have a 32bit controller drop in for uno based laser etcher and cnc machines.

### Feature Description

grbl cnc/laser etching.

### Other Approaches

wemos d1 r32

### How I Can Help

wemos d1 r32

**Comment by MitchBradley** [comment]
FluidNC does not require recompiling to adapt to a different board.  It is configured via a text file that describes, among other things, the mapping of pins to functions.  Please read [the wiki](http://wiki.fluidnc.com/) which tells all about that.
