### ISSUE TITLE
Feature: Can we pick the label of the axis??

### ISSUE THREAD

**Issue by brakthehun** [bdring/FluidNC#808]
### Machine Context

I built a hotwire foam cnc.
Right now it is 3-axis (X Y A)
Most howire CAM outputs X Y U V A
It would be nice tro be able to name any axis what ever we want.
I have also built a clay printer and it doesn't need any heat management but it does need a E axis

### Feature Description

  axes:
    x:
      steps_per_mm: 160.000
      etc
      
    u:
      steps_per_mm: 160.00

### Other Approaches

I could use the find and replace funcion in notepad like a chump.

### How I Can Help

The back end can assume the right order and relabel axes(translate) incoming gcode.

**Comment by MitchBradley** [comment]
It is very unlikely that we will add this feature.  This is the first time that anyone has asked for it.  It would be a lot of work to find all the places in the code that assume axis names, and misconfigurations could cause a lot of confusion.
