### ISSUE TITLE
Feature: command toolchange execute macro

### ISSUE THREAD

**Issue by kjk25** [bdring/FluidNC#842]
### Machine Context

When i zry to send my gcode the machine ignore my m6 T1 commands dose not wait for manual change, and cant execute macros.
Would be good to have desitions what to di eith the m6 for example wait until tool is changed, drive to toolchange pos. 

Or miss i something ?
Kai

### Feature Description

1

### Other Approaches

2

### How I Can Help

3

**Comment by mac7988** [comment]
If you need some help please follow the rules of this Repo. How can anyone help if you don't post all the info??

**Comment by bdring** [comment]
http://wiki.fluidnc.com/en/features/atc
