### ISSUE TITLE
Feature: Configuration for MKS LTS 1.1 

### ISSUE THREAD

**Issue by ckocyigit** [bdring/FluidNC#857]
### Machine Context

I have a simple XY 400x400mm Laser engraver/cutter from makibes with the model x1 but I would guess that those are just some rebranded standard chassis etc.

### Feature Description

The machine utilizes a long term support kind of makerbases motherboards.

Makerbase MKS LTS 1.1 

I could successfully install FluidNC on it and also running it was no problem. Head movement worked however Laser and SD card did not. I've started plotting down the pinouts and connections and it seems to be very similiar to the dlc32 boards.

It would be awesome if someone, who is in the matter could adapt for this board.

### Other Approaches

Example config for this board.

### How I Can Help

I can share pictures and try to measure and plot connections on the board,

**Comment by MitchBradley** [comment]
Another thing that would be awesome would be if the manufacturers that make hardware that depends on our software would contribute money to our project, to defray at least some of the costs that we incur in supporting yet another hardware variant every week or so.  But that is not likely to happen, so the next most awesome thing would be if more users would donate.

**Comment by ckocyigit** [comment]
@dorsi90 Thank you very much

I've uploaded it and it seems to be working for the laser.
Unfortunately SDCard is not being recognized. I will check if the GPIO's corrospond correctly.
(I've also formatted as suggested by FluidNC)

You should MR this file into the example folder for future users 😄

**Comment by ckocyigit** [comment]
I've tried a different sd card.
It seems to be something different. Log says: [MSG:ERR: sdmmc_card_init failed code 0x107] on either sdcard.

Yes I know that, its currently outside of the frame. Do you have discord/email for further messaging?

**Comment by dorsi90** [comment]
@ckocyigit yes you can write me to info@tronica.it
Are sd cards formatted as fat32?

**Comment by MitchBradley** [comment]
You can try adding ` frequency_hz: 1000000` to the `sdcard:` section, indented the same as the other items under sdcard:  That might help.

You can also try reformatting the SD Card using a small allocation unit size.  Large allocation units might require larger amounts of RAM than the ESP32 has.

Some MicroSD cards simply do not support SPI mode at all.  For those the error is often 0x108 .  It can be hard to tell in advance which cards support SPI mode - but older, smaller cards in the 4GB range are often good.  Newer, larger cards typically have lots of advanced features and can drop support for legacy modes like SPI.

**Comment by oldschool91** [comment]
Hello, my TTS 55 10w burner is also equipped with an MKS LTS v1 card, and I would like to be able to control my air assit with the SCL output as in this tutorial "Trees Totem S / Air Assist Control - #9 by Trek2120 " , but the commands are not active in the firmware is it possible to modify the firmware? If yes, how?
I contacted MKS who referred me to TTS and TTS told me that they did not have the firmware...
Thanks for your help
Christopher

**Comment by bdring** [comment]
Most people add air assist via coolant commands.

Please read the wiki to learn how to add this to your config. It is quite easy and does not require a compile.

**Comment by oldschool91** [comment]
I did as in the wiki, but it does not work on my card, hence my question the firmware should not allow it

**Comment by oldschool91** [comment]
ok not to do anything stupid or I create a new post? I am a little lost

**Comment by oldschool91** [comment]
I just figured out how to open a post I won't bother you here anymore.
Sorry

**Comment by Lusui8787** [comment]
purchased a MAKIBES X1 laser engraver. Connected with Laser GRBL program. But I don't understand where to get the GCODE configuration file for this laser. And therefore the laser head itself moves, but the laser itself does not appear. Help how to fix it. Thank you sincerely.

![Laser Makibes in GRBL program](https://github.com/bdring/FluidNC/assets/141737945/d78d17a6-7455-4515-9f1a-62556e81d8c4)

**Comment by MitchBradley** [comment]
The signon message says "SimpleLaser 1.1h".  This GitHub repo is for FluidNC, not SimpleLaser.  Ask the people who sold you the machine.

**Comment by Lusui8787** [comment]
Thank you

**Comment by Mtjkrjcr** [comment]
Hello, could someone send me a picture of the motherboard?

**Comment by ckocyigit** [comment]
> Hello, could someone send me a picture of the motherboard?

![20231228_172413.jpg](https://github.com/bdring/FluidNC/assets/60385015/3a00bb48-42c0-49a6-968f-24815b794cb1)

![20231228_172421.jpg](https://github.com/bdring/FluidNC/assets/60385015/af32e28e-b1b4-45ef-b4d3-44b268e4f8f5)

**Comment by denizzzka** [comment]
Interested in it too: it installed by manufacturer Flyingbear into Laserman engravers

Also, here is display connector:
![image](https://github.com/user-attachments/assets/6f91e56f-a1c1-48a2-b973-a46ebaf79ccf)

Display "Makerbase" connected by two rainbow wires: 
![image](https://github.com/user-attachments/assets/cb74c07c-8851-4e2c-9eaf-c3910335b9c9)

**Comment by denizzzka** [comment]
Also, they use Z axis to obtain info from the fire (PIR?) sensor: 
![image](https://github.com/user-attachments/assets/25f64086-419b-4658-b019-30b9aee4d243)

If fire burns on table sensor stops system. Maybe this is important, I don't know maybe this is common practice

**Comment by denizzzka** [comment]
@ckocyigit can you publish your binary for this controller? Thank you!
