### ISSUE TITLE
Problem: Wrong resistor lables on the board

### ISSUE THREAD

**Issue by Saschko2000** [bdring/FluidNC#861]
### Controller Board

FluidNC Pen/Laser CNC Controller (SPI)

### Machine Description

https://oshwlab.com/bdring/tmc2130-2-axis

### Configuration file

```yaml
doesn't matter
```

### Startup Messages

```text
doesn't matter
```

### What happened?

The lables for 2 resitor pairs are switched.
- R17 / R19
- R18 / R20

### Other Information

The lables for 2 resitor pairs are switched.
- R17 / R19
- R18 / R20

**Comment by bdring** [comment]
Fixed, The robot that builds these does not car :-)

**Comment by Saschko2000** [comment]
Thanks for the fast fix :-)

I ordered 5 boards from PCBWay, and they are all placed wrong :-(
And they are really tiny to hand solder ;-)

**Comment by bdring** [comment]
The 1 click order from JLC always worked and probably cheaper.
