### ISSUE TITLE
Feature: Please add 3D printer mode

### ISSUE THREAD

**Issue by SeamusCheng** [bdring/FluidNC#909]
### Machine Context

I compared fluidnc with Marlin and found that adding a few Marlin M commands to fluidnc can replace Marlin's control of 3D printers. The most frustrating thing is that Marlin is very unfriendly to ESP32, and it leans more towards the underperforming mega2560, and Marlin doesn't has !  feed hold function is very unfriendly to serial screen players.

### Feature Description

I compared fluidnc with Marlin and found that adding a few Marlin M commands to fluidnc can replace Marlin's control of 3D printers. The most frustrating thing is that Marlin is very unfriendly to ESP32, and it leans more towards the underperforming mega2560, and Marlin doesn't has !  feed hold function is very unfriendly to serial screen players.

### Other Approaches

I compared fluidnc with Marlin and found that adding a few Marlin M commands to fluidnc can replace Marlin's control of 3D printers. The most frustrating thing is that Marlin is very unfriendly to ESP32, and it leans more towards the underperforming mega2560, and Marlin doesn't has !  feed hold function is very unfriendly to serial screen players.

### How I Can Help

I compared fluidnc with Marlin and found that adding a few Marlin M commands to fluidnc can replace Marlin's control of 3D printers. The most frustrating thing is that Marlin is very unfriendly to ESP32, and it leans more towards the underperforming mega2560, and Marlin doesn't has !  feed hold function is very unfriendly to serial screen players.

**Comment by bdring** [comment]
We are trying to make FluidNC the best firmware for machines like routers, laser, etc. There are already good firmwares for 3D printing. We also run the risk of breaking our compatibility with grbl gcode senders. Marlin interprets some commands differently.

<http://wiki.fluidnc.com/en/features/supported_gcodes>

We have no plans for 3D printing or "being like Marlin" at this time.
