### ISSUE TITLE
Default password for wifi AP

### ISSUE THREAD

**Issue by krishchan007** [bdring/FluidNC#96]
Default password for wifi AP 123456768 is not working. Any solutions?

**Comment by bdring** [comment]
Get rid of the extra 6?

**Comment by krishchan007** [comment]
Solved. In wiki the password shown is 123456768 which is incorrect and the right one is12345678

**Comment by krishchan007** [comment]
Why an extra 6 in wiki?

**Comment by bdring** [comment]
Fixed. Our editorial staff must have missed that.

**Comment by krishchan007** [comment]
Thanks
