### ISSUE TITLE
Fluidterm 3.7.4 crashing on MacOs

### ISSUE THREAD

**Issue by FrankNz** [bdring/FluidNC#973]
### Wiki Search Terms

Fluidterm >= 3.7.1 Crashing

### Controller Board

n/a

### Machine Description

n/a

### Input Circuits

```yaml
n/a
```

### Configuration file

```yaml
n/a
```

### Startup Messages

```text
n/a
```

### User Interface Software

Fluidterm

### What happened?

Running on MacOs Ventura 13.4.1(c)
The problem below was occurring before on 13.4.0

- Fluidterm >= 3.7.1 crashes after asking for a port, see attached image. I can still use Ctrl+] to quit Fluidterm.
- Fluidterm = 3.7.0 works OK, see attached image.

The images are of connections to the same controller. Not simultaneously.

### GCode File

na

### Other Information

<img width="697" alt="Screenshot 2023-07-17 at 4 31 03 PM" src="https://github.com/bdring/FluidNC/assets/10928777/88a79ad8-9995-44c5-8d67-7022596cda7a">
<img width="1061" alt="Screenshot 2023-07-17 at 4 18 08 PM" src="https://github.com/bdring/FluidNC/assets/10928777/c836cb0b-b4ec-46b4-ae73-07fbf4f9be40">

**Comment by MitchBradley** [comment]
Please use a more useful title than "n/a".

The change in fluidterm.py between 3.7.0 and 3.7.1 occurred as a result of #911 and #927, authored by @Alex-CodeLab .  As the author of the most recent change, it is his responsibility to address the problems.

**Comment by FrankNz** [comment]
I stand corrected, sorry.

**Comment by FrankNz** [comment]
I should have added I'm on Python 3.11.4, pip 23.1.2

**Comment by Alex-CodeLab** [comment]
@FrankNz Does that happen all the time, or sometimes?

There seems to be some strange racecondition in the threads.

Here I run the same code 3 times, all with different results 
(1st: lock, 2nd: crash, 3rd: working)
![Screenshot from 2023-07-21 13-48-59](https://github.com/bdring/FluidNC/assets/1678423/27d0686b-89bc-4c2d-82b9-cb96a3fba215)

**Comment by Alex-CodeLab** [comment]
Adding halve a second delay when starting the `reader()` seems to fix it. 
@FrankNz could you try if this helps? 
https://github.com/Alex-CodeLab/FluidNC/commit/bd9aca0ec47dc48d65c1a466fcc5751f931575c0

**Comment by FrankNz** [comment]
HI,
For me it happens every time.
I have attached a clip of my Mac below.
I have received your subsequent email 

Thank you for providing a potential fix, I’ll try your it later today and get back to you.

Regards 
Frank

￼

**Comment by FrankNz** [comment]
HI,
For me it happens every time.
I have attached a clip of my Mac below.
I have received your subsequent email

Thank you for providing a potential fix, I’ll try your it later today and get back to you.

Regards
Frank
<img width="279" alt="MyMac" src="https://github.com/bdring/FluidNC/assets/10928777/31ceb809-aeeb-4075-bb1a-b198122ccb89">

**Comment by FrankNz** [comment]
It is working now, Thank you.
