### ISSUE TITLE
Problem: Docs spelling issue

### ISSUE THREAD

**Issue by V1EngineeringInc** [bdring/FluidNC#978]
### Wiki Search Terms

RMT

### Controller Board

jackpot

### Machine Description

mpcnc

### Configuration file

```yaml
No config needed
```

### Startup Messages

```text
No needed
```

### What happened?

http://wiki.fluidnc.com/en/config/axes#stepping in this paragraph the RMT link is spelled RTM

**Comment by MitchBradley** [comment]
Fixed
